-- //FILE SUGARCRM flav=ent ONLY 
-- project
ALTER TABLE PROJECT DROP (ESTIMATED_START_DATE, STATUS, PRIORITY, IS_TEMPLATE, ESTIMATED_END_DATE);

-- project_task
UPDATE PROJECT_TASK SET PARENT_ID=PROJECT_ID;
ALTER TABLE PROJECT_TASK DROP (PROJECT_ID, PROJECT_TASK_ID, RESOURCE_ID, PREDECESSORS, TIME_FINISH, DATE_FINISH, DURATION, DURATION_UNIT, ACTUAL_DURATION, PARENT_TASK_ID);
ALTER TABLE PROJECT_TASK DROP COLUMN TIME_START;
ALTER TABLE PROJECT_TASK ADD (TIME_START DATE);
UPDATE PROJECT_TASK SET TIME_START=TIME_START_BACKED;
ALTER TABLE PROJECT_TASK DROP COLUMN TIME_START_BACKED;

ALTER TABLE PROJECT_TASK MODIFY(PARENT_ID VARCHAR2(36 CHAR) NOT NULL);

UPDATE PROJECT_TASK SET MILESTONE_FLAG="on" WHERE MILESTONE_FLAG="1";
UPDATE PROJECT_TASK SET MILESTONE_FLAG="off" WHERE MILESTONE_FLAG="0";