<?php

$dictionary['Contact']['fields']['geo_mobility_country_1_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_1_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_1_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_1_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_2_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_2_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_2_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_2_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_3_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_3_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_3_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_3_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_4_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_4_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_4_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_4_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_5_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_5_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_5_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_5_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_6_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_6_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_6_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_6_c',
        'values' =>
            array (
                '' =>
                    array (
                        0 => '',
                    ),
                'Americas' =>
                    array (
                        0 => '',
                        1 => 'BRAZIL',
                        2 => 'CANADA',
                        3 => 'COLOMBIA',
                        4 => 'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        0 => '',
                        1 => 'AUSTRALIA',
                        2 => 'CHINA',
                        3 => 'HONG KONG',
                        4 => 'INDIA',
                        5 => 'INDONESIA',
                        6 => 'JAPAN',
                        7 => 'MALAYSIA',
                        8 => 'PHILIPPINES',
                        9 => 'SINGAPORE',
                        10 => 'KOREA, SOUTH',
                        11 => 'TAIWAN',
                        12 => 'THAILAND',
                    ),
                'CEE' =>
                    array (
                        0 => '',
                        1 => 'AUSTRIA',
                        2 => 'BULGARIA',
                        3 => 'CROATIA',
                        4 => 'CZECH REPUBLIC',
                        5 => 'POLAND',
                        6 => 'ROMANIA',
                        7 => 'RUSSIA',
                        8 => 'SLOVAKIA',
                        9 => 'TURKEY',
                    ),
                'Africa' =>
                    array (
                        0 => '',
                        1 => 'KENYA',
                        2 => 'LEBANON',
                        3 => 'MOROCCO',
                        4 => 'REUNION',
                        5 => 'SAUDI ARABIA',
                        6 => 'SOUTH AFRICA',
                        7 => 'TUNISIA',
                        8 => 'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        0 => '',
                        1 => 'BELGIUM',
                        2 => 'FRANCE',
                        3 => 'GERMANY',
                        4 => 'GREECE',
                        5 => 'IRELAND',
                        6 => 'ITALY',
                        7 => 'LUXEMBOURG',
                        8 => 'NORWAY',
                        9 => 'SPAIN',
                        10 => 'SWEDEN',
                        11 => 'SWITZERLAND',
                        12 => 'UNITED KINGDOM',
                        13 => 'DENMARK',
                        14 => 'NETHERLANDS',
                        15 => 'FINLAND',
                        16 => 'PORTUGAL',
                    ),
                'Other' =>
                    array (
                        0 => 'OTHER',
                    ),
            ),
    ),
);
