<?php
 // created: 2020-11-10 17:25:33
$dictionary['Contact']['fields']['gtb_cluster_c'] = [
'labelValue' => 'Cluster',
      'dependency' => '',
      'required_formula' => '',
      'visibility_grid' => '',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'gtb_cluster_c',
      'vname' => 'LBL_GTB_CLUSTER_C',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'gtb_cluster_list',
      'default' => '',
      'id' => 'bd3fc388-2379-11eb-a24f-0242ac150007',
      'custom_module' => 'Contacts',
];
 ?>
