<?php
 // created: 2020-11-11 20:33:04
$dictionary['Contact']['fields']['functional_mobility_c'] = [
    'labelValue' => 'Functional Mobility',
    'dependency' => '',
    'required_formula' => '',
    'visibility_grid' => '',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'functional_mobility_c',
    'vname' => 'LBL_FUNCTIONAL_MOBILITY_C',
    'type' => 'multienum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'options' => 'gtb_function_list',
    'default' => NULL,
    'isMultiSelect' => true,
    'id' => '19b0f856-245d-11eb-b7a2-0242ac140007',
    'custom_module' => 'Contacts',
];
 ?>
