<?php

$dictionary['Contact']['fields']['geo_mobility_country_1_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_1_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_1_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_1_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_2_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_2_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_2_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_2_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_3_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_3_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_3_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_3_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_4_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_4_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_4_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_4_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_5_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_5_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_5_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_5_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);


$dictionary['Contact']['fields']['geo_mobility_country_6_c'] = array (
    'required' => true,
    'name' => 'geo_mobility_country_6_c',
    'vname' => 'LBL_GEO_MOBILITY_COUNTRY_6_C',
    'type' => 'multienum',
    'isMultiSelect' => true,
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'dependency' => false,
    'visibility_grid' => array (
        'trigger' => 'geo_mobility_region_6_c',
        'values' =>
            array (
                '' =>
                    array (
                        '',
                    ),
                'Americas' =>
                    array (
                        '',
                        'All',
                        'BRAZIL',
                        'CANADA',
                        'COLOMBIA',
                        'USA',
                    ),
                'Asia_Pacific' =>
                    array (
                        '',
                        'All',
                        'AUSTRALIA',
                        'CHINA',
                        'HONG KONG',
                        'INDIA',
                        'INDONESIA',
                        'JAPAN',
                        'MALAYSIA',
                        'PHILIPPINES',
                        'SINGAPORE',
                        'KOREA, SOUTH',
                        'TAIWAN',
                        'THAILAND',
                    ),
                'CEE' =>
                    array (
                        '',
                        'All',
                        'AUSTRIA',
                        'BULGARIA',
                        'CROATIA',
                        'CZECH REPUBLIC',
                        'POLAND',
                        'ROMANIA',
                        'RUSSIA',
                        'SLOVAKIA',
                        'TURKEY',
                    ),
                'Africa' =>
                    array (
                        '',
                        'All',
                        'KENYA',
                        'LEBANON',
                        'MOROCCO',
                        'REUNION',
                        'SAUDI ARABIA',
                        'SOUTH AFRICA',
                        'TUNISIA',
                        'UNITED ARAB EMIRATES',
                    ),
                'Europe' =>
                    array (
                        '',
                        'All',
                        'BELGIUM',
                        'DENMARK',
                        'FINLAND',
                        'FRANCE',
                        'GERMANY',
                        'GREECE',
                        'IRELAND',
                        'ITALY',
                        'LUXEMBOURG',
                        'NETHERLANDS',
                        'NORWAY',
                        'PORTUGAL',
                        'SPAIN',
                        'SWEDEN',
                        'SWITZERLAND',
                        'UNITED KINGDOM',
                    ),
                'Other' =>
                    array (
                        'OTHER',
                    ),
                'Worldwide' =>
                    array(
                        'All',
                    ),
            ),
    ),
);
