<?php

$dictionary['Contact']['fields']['gender_c'] = [
    'labelValue' => 'Gender',
    'dependency' => '',
    'required_formula' => '',
    'visibility_grid' => '',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'gender_c',
    'vname' => 'LBL_GENDER_C',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'gtb_gender_list',
    'default' => NULL,
    'custom_module' => 'Contacts',
    'id' => 'bb02d5ce-2374-11eb-b6c0-0242ac150007',
];
