<?php

$dictionary['Contact']['fields']['geo_mobility_region_1_c'] = array (
  'required' => true,
  'name' => 'geo_mobility_region_1_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_1_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);


$dictionary['Contact']['fields']['geo_mobility_region_2_c'] = array (
  'required' => false,
  'name' => 'geo_mobility_region_2_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_2_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);


$dictionary['Contact']['fields']['geo_mobility_region_3_c'] = array (
  'required' => false,
  'name' => 'geo_mobility_region_3_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_3_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);


$dictionary['Contact']['fields']['geo_mobility_region_4_c'] = array (
  'required' => false,
  'name' => 'geo_mobility_region_4_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_4_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);


$dictionary['Contact']['fields']['geo_mobility_region_5_c'] = array (
  'required' => false,
  'name' => 'geo_mobility_region_5_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_5_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);


$dictionary['Contact']['fields']['geo_mobility_region_6_c'] = array (
  'required' => false,
  'name' => 'geo_mobility_region_6_c',
  'vname' => 'LBL_GEO_MOBILITY_REGION_6_C',
  'type' => 'enum',
  'massupdate' => true,
  'hidemassupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => '1',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'default' => '',
  'calculated' => false,
  'len' => 100,
  'size' => '20',
  'options' => 'gtb_region_list',
  'dependency' => false,
);

