<?php
 // created: 2020-11-13 03:54:53
$dictionary['Contact']['fields']['gtb_function_match_c'] = [
    'labelValue' => 'Function Match',
    'dependency' => '',
    'required_formula' => '',
    'visibility_grid' => '',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'gtb_function_match_c',
    'vname' => 'LBL_GTB_FUNCTION_MATCH_C',
    'type' => 'multienum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'options' => 'gtb_function_list',
    'default' => NULL,
    'isMultiSelect' => true,
    'id' => 'fc84e1a4-2563-11eb-9006-0242ac140007',
    'custom_module' => 'Contacts',
];
 ?>
