<?php
 // created: 2020-11-11 20:43:23
$dictionary['Contact']['fields']['geo_mobility_c'] = [
    'labelValue' => 'Geographical Mobility',
    'dependency' => '',
    'required_formula' => '',
    'visibility_grid' => '',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'geo_mobility_c',
    'vname' => 'LBL_GEO_MOBILITY_C',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'gtb_geo_mobility_list',
    'default' => NULL,
    'id' => '8aaad88c-245e-11eb-8b2e-0242ac140007',
    'custom_module' => 'Contacts',
];
 ?>
