<?php
 // created: 2020-11-11 20:37:12
$dictionary['Contact']['fields']['language_6_c'] = [
    'labelValue' => 'Language',
    'dependency' => '',
    'required_formula' => '',
    'visibility_grid' => '',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'language_6_c',
    'vname' => 'LBL_LANGUAGE',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'gtb_language_list',
    'default' => NULL,
    'id' => 'ad8a1468-245d-11eb-b53c-0242ac140007',
    'custom_module' => 'Contacts',
];
 ?>
