@BR @pr
Feature: Global Search

  Background:
    Given I use default account
    #default account means admin/asdf I think
    Given I launch App with config: "skipTutorial"
    #launch web browser and type the Sugar in the address bar without login

    Given Accounts records exist:
      | *name               | tag                               | email                           |
      | ANewAccount_By_GL03 | accountTag,sharedTag,tagByNumber3 | alias.jim@example.com (primary) |
      | ANewAccount_By_GL02 | accountTag,sharedTag,tagByNumber2 | johnnie@gmail.com (primary)     |
      | ANewAccount_By_GL01 | accountTag,SharedTag,tagByNumber1 | abc@cnn.com (primary)           |

    Given Contacts records exist:
      | *first_name         | last_name | tag                               | email                                                              |
      | New_Contact03_By_GL | Lando     | contactTag,sharedTag,tagByNumber3 | hr.info.hr@example.com (primary),esther_super_lady@ventureland.com |
      | New_Contact02_By_GL | Lando     | contactTag,sharedTag,tagByNumber2 | im.im@example.name (primary),jelle_vink_architect@gmail.com        |
      | New_Contact01_By_GL | Lando     | contactTag,sharedTag,tagByNumber1 | david_wheeler@gmail.com (primary),info98@examle.com.uk             |


  @xxx
  Scenario Outline: Global search should return correct results

    Given I open search view and login
    When I choose modules "<modulesToSearch>" to search
    When I search for text "<textToSearch>" with tags "<tagsToSearch>" in globalsearch before confirming
    Then I should see list of highlighted items "<expectedHighlightedItemsList>" under the search type ahead results
    When I confirm to search whatever in the search input box
    Then I should see "<expectedNumOfMatch>" displayed as number of match under search result
    Then I should see search result filters "<filtersToSearch>" under the Filter right hand side pane


    Examples:
      | modulesToSearch         | tagsToSearch                      | filtersToSearch                                   | textToSearch                                       | expectedNumOfMatch | expectedHighlightedItemsList                                                                                                                                                                     |
      | all                     | tagByNumber2                      | Created by Me (1),Modified by Me (1)              | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts,Contacts       | tagByNumber3,contactTag,sharedTag | Created by Me (1),Modified by Me (1),Contacts (1) | ( johnn OR esther_su ) NOT gmail                   | 1                  |                                                                                                                                                                                                  |
      | all                     | accountTag                        | Modified by Me (1),Created by Me (1),Accounts (1) | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     | sharedTag                         | Created by Me (1),Modified by Me (1)              | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts                | sharedTag                         |                                                   | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts                | tagByNumber2                      |                                                   | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Leads,Contacts,Accounts | tagByNumber2                      |                                                   | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts                | tagByNumber3                      |                                                   | johnn                                              | 0                  |                                                                                                                                                                                                  |
      | Contacts                | sharedTag                         |                                                   | johnn                                              | 0                  |                                                                                                                                                                                                  |
      | Leads                   | sharedTag                         |                                                   | johnn                                              | 0                  |                                                                                                                                                                                                  |
      | all                     | accountTag,contactTag             |                                                   | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     | contactTag                        |                                                   | johnn                                              | 0                  |                                                                                                                                                                                                  |
      | Accounts,Contacts,Leads |                                   |                                                   | johnn                                              | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Contacts,Leads          |                                   |                                                   | johnn                                              | 0                  |                                                                                                                                                                                                  |
      | Contacts,Leads          |                                   |                                                   | johnn OR david                                     | 1                  | david_wheeler@gmail.com                                                                                                                                                                          |
      | all                     |                                   |                                                   | johnn AND david                                    | 0                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | johnnie                                            | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     |                                   |                                                   | johnnie AND esther_super                           | 0                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | johnnie OR esther_super                            | 2                  | johnnie@gmail.com,esther_super_lady@ventureland.com                                                                                                                                              |
      | all                     |                                   |                                                   | johnnie \| esther_super                            | 2                  | johnnie@gmail.com,esther_super_lady@ventureland.com                                                                                                                                              |
      | all                     |                                   |                                                   | ( johnn OR esther_su ) NOT gmail                   | 1                  |                                                                                                                                                                                                  |
      | Accounts,Contacts       | tagByNumber3                      | Created by Me (1),Modified by Me (1),Contacts (1) | ( johnn OR esther_su ) NOT gmail                   | 1                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | ( johnn \| esther_su ) NOT gmail                   | 1                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | ( johnn OR esther_su ) - gmail                     | 1                  |                                                                                                                                                                                                  |
      | Contacts                |                                   |                                                   | ( johnn \| esther_su ) - gmail                     | 1                  |                                                                                                                                                                                                  |
      | Accounts                |                                   |                                                   | ( johnn \| esther_su ) - gmail                     | 0                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | new & by & com & accou                             | 3                  | ANewAccount_By_GL01,abc@cnn.com,ANewAccount_By_GL03,alias.jim@example.com,ANewAccount_By_GL02,johnnie@gmail.com                                                                                  |
      | all                     | tagByNumber1,tagByNumber3         |                                                   | new & by & com                                     | 4                  | david_wheeler@gmail.com,New_Contact01_By_GL,hr.info.hr@example.com,New_Contact03_By_GL,ANewAccount_By_GL01,abc@cnn.com,ANewAccount_By_GL03,alias.jim@example.com                                 |
      | Accounts                |                                   |                                                   | new & by & com                                     | 3                  | ANewAccount_By_GL01,abc@cnn.com,ANewAccount_By_GL03,alias.jim@example.com,ANewAccount_By_GL02,johnnie@gmail.com                                                                                  |
      | Contacts                |                                   |                                                   | new & by & com                                     | 3                  | david_wheeler@gmail.com,info98@examle.com.uk,New_Contact01_By_GL,New_Contact02_By_GL,jelle_vink_architect@gmail.com,hr.info.hr@example.com,esther_super_lady@ventureland.com,New_Contact03_By_GL |
      | all                     |                                   |                                                   | (new & by & com) - contact                         | 3                  | ANewAccount_By_GL01,abc@cnn.com,ANewAccount_By_GL03,alias.jim@example.com,ANewAccount_By_GL02,johnnie@gmail.com                                                                                  |
      | all                     |                                   |                                                   | NOT account AND (new & by & com)                   | 3                  | david_wheeler@gmail.com,info98@examle.com.uk,New_Contact01_By_GL,hr.info.hr@example.com,esther_super_lady@ventureland.com,New_Contact03_By_GL,New_Contact02_By_GL,jelle_vink_architect@gmail.com |
      | all                     |                                   |                                                   | (NOT account) AND (NOT name) AND (new & by & com ) | 2                  | david_wheeler@gmail.com,info98@examle.com.uk,New_Contact01_By_GL,hr.info.hr@example.com,esther_super_lady@ventureland.com,New_Contact03_By_GL                                                    |
      | all                     |                                   |                                                   | NOT admin & - archiv                               | 6                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | new & jim & com & exam & alia NOT sally            | 1                  | ANewAccount_By_GL03,alias.jim@example.com                                                                                                                                                        |
      | Accounts                |                                   |                                                   | johnnie                                            | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts,Contacts       |                                   |                                                   | johnnie                                            | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Contacts                |                                   |                                                   | johnnie                                            | 0                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | johnnie@                                           | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | Accounts                |                                   |                                                   | johnnie@                                           | 1                  | johnnie@gmail.com                                                                                                                                                                                |
#      | all                     |                                   |                                                   | johnnie@g                                          | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     |                                   |                                                   | johnnie@gmail.                                     | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     |                                   |                                                   | johnnie@gmail.co                                   | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     |                                   |                                                   | johnnie@gmail.com                                  | 1                  | johnnie@gmail.com                                                                                                                                                                                |
      | all                     |                                   |                                                   | gmail.com                                          | 3                  | johnnie@gmail.com,david_wheeler@gmail.com,jelle_vink_architect@gmail.com                                                                                                                         |
      | all                     |                                   |                                                   | esther_super                                       | 1                  | esther_super_lady@ventureland.com                                                                                                                                                                |
      | all                     |                                   |                                                   | esther_super_lady@ventur                           | 1                  | esther_super_lady@ventureland.com                                                                                                                                                                |
      | all                     |                                   |                                                   | esther_super_lady@vent                             | 1                  | esther_super_lady@ventureland.com                                                                                                                                                                |
      | all                     |                                   |                                                   | esther_super_lady@ventureland.com                  | 1                  | esther_super_lady@ventureland.com                                                                                                                                                                |
      | all                     |                                   |                                                   | ANewAcc                                            | 3                  | ANewAccount_By_GL01,ANewAccount_By_GL02,ANewAccount_By_GL03                                                                                                                                      |
      | Contacts                |                                   |                                                   | ANewAcc                                            | 0                  |                                                                                                                                                                                                  |
      | all                     |                                   |                                                   | ccount_By_GL                                       | 3                  | ANewAccount_By_GL01,ANewAccount_By_GL02,ANewAccount_By_GL03                                                                                                                                      |
      | Accounts                |                                   |                                                   | count_By_GL01                                      | 1                  | ANewAccount_By_GL01                                                                                                                                                                              |
