<?php
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Enterprise Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/products/sugar-enterprise-eula.html
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2010 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
$dictionary['Orders'] = array(
	'table'=>'orders',
	'audited'=>true,
	'fields'=>array (
       'id' =>
        array (
            'name' => 'id',
            'vname' => 'LBL_NAME',
            'type' => 'id',
            'required'=>true,
            'reportable'=>false,
            'comment' => 'Unique identifier'
        ),  
'order_id' => 
  array (
    'name' => 'order_id',
    'vname' => 'LBL_NUMBER',
    'type' => 'int',
    'required' => true,     
    'len' => '11',
    'isnull' => 'false',
    'auto_increment' => false,
    'comment' => 'Visible order identifier',
    'disable_num_format' => true,
  ),
  'user_id' => 
  array (
    'required' => '1',
    'name' => 'user_id',
    'vname' => 'LBL_USER_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '1',
  ),
  'username' => 
  array (
    'required' => false,
    'name' => 'username',
    'vname' => 'LBL_USERNAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'total' => 
  array (
    'required' => false,
    'name' => 'total',
    'vname' => 'LBL_TOTAL',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '18',
    'size' => '20',
    'precision' => '2',
  ),
  'subtotal' => 
  array (
    'required' => false,
    'name' => 'subtotal',
    'vname' => 'LBL_SUBTOTAL',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '18',
    'size' => '20',
    'precision' => '2',
  ),
  'discount' => 
  array (
    'required' => false,
    'name' => 'discount',
    'vname' => 'LBL_DISCOUNT',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '18',
    'size' => '20',
    'precision' => '2',
  ),
  'tax' => 
  array (
    'required' => false,
    'name' => 'tax',
    'vname' => 'LBL_TAX',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '18',
    'size' => '20',
    'precision' => '2',
  ),
  'status' => 
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Queued',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
    'options' => 'order_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'payment_method' => 
  array (
    'required' => false,
    'name' => 'payment_method',
    'vname' => 'LBL_PAYMENT_METHOD',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Credit Card',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
    'options' => 'payment_method_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'notes' => 
  array (
    'required' => false,
    'name' => 'notes',
    'vname' => 'LBL_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'title' => 
  array (
    'required' => false,
    'name' => 'title',
    'vname' => 'LBL_TITLE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'first_name' => 
  array (
    'required' => false,
    'name' => 'first_name',
    'vname' => 'LBL_FIRST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'last_name' => 
  array (
    'required' => false,
    'name' => 'last_name',
    'vname' => 'LBL_LAST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'company_name' => 
  array (
    'required' => false,
    'name' => 'company_name',
    'vname' => 'LBL_COMPANY_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'phone' => 
  array (
    'required' => false,
    'name' => 'phone',
    'vname' => 'LBL_PHONE',
    'type' => 'phone',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'fax' => 
  array (
    'required' => false,
    'name' => 'fax',
    'vname' => 'LBL_FAX',
    'type' => 'phone',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'email' => 
  array (
    'required' => false,
    'name' => 'email',
    'vname' => 'LBL_EMAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_title' => 
  array (
    'required' => false,
    'name' => 'billing_title',
    'vname' => 'LBL_BILLING_TITLE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_first_name' => 
  array (
    'required' => false,
    'name' => 'billing_first_name',
    'vname' => 'LBL_BILLING_FIRST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_last_name' => 
  array (
    'required' => false,
    'name' => 'billing_last_name',
    'vname' => 'LBL_BILLING_LAST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_address_city' => 
  array (
    'required' => false,
    'name' => 'billing_address_city',
    'vname' => 'LBL_BILLING_ADDRESS_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'billing_address_state' => 
  array (
    'required' => false,
    'name' => 'billing_address_state',
    'vname' => 'LBL_BILLING_ADDRESS_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'billing_address_postalcode' => 
  array (
    'required' => false,
    'name' => 'billing_address_postalcode',
    'vname' => 'LBL_BILLING_ADDRESS_POSTALCODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 20,
    'size' => '20',
  ),
  'billing_address_country' => 
  array (
    'required' => false,
    'name' => 'billing_address_country',
    'vname' => 'LBL_BILLING_ADDRESS_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'billing_address' => 
  array (
    'required' => false,
    'name' => 'billing_address',
    'vname' => 'LBL_BILLING_ADDRESS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_city' => 
  array (
    'required' => false,
    'name' => 'billing_city',
    'vname' => 'LBL_BILLING_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_state' => 
  array (
    'required' => false,
    'name' => 'billing_state',
    'vname' => 'LBL_BILLING_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_country' => 
  array (
    'required' => false,
    'name' => 'billing_country',
    'vname' => 'LBL_BILLING_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_zip_code' => 
  array (
    'required' => false,
    'name' => 'billing_zip_code',
    'vname' => 'LBL_BILLING_ZIP_CODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_title' => 
  array (
    'required' => false,
    'name' => 'shipping_title',
    'vname' => 'LBL_SHIPPING_TITLE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_first_name' => 
  array (
    'required' => false,
    'name' => 'shipping_first_name',
    'vname' => 'LBL_SHIPPING_FIRST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_last_name' => 
  array (
    'required' => false,
    'name' => 'shipping_last_name',
    'vname' => 'LBL_SHIPPING_LAST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_address_city' => 
  array (
    'required' => false,
    'name' => 'shipping_address_city',
    'vname' => 'LBL_SHIPPING_ADDRESS_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'shipping_address_state' => 
  array (
    'required' => false,
    'name' => 'shipping_address_state',
    'vname' => 'LBL_SHIPPING_ADDRESS_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'shipping_address_postalcode' => 
  array (
    'required' => false,
    'name' => 'shipping_address_postalcode',
    'vname' => 'LBL_SHIPPING_ADDRESS_POSTALCODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 20,
    'size' => '20',
  ),
  'shipping_address_country' => 
  array (
    'required' => false,
    'name' => 'shipping_address_country',
    'vname' => 'LBL_SHIPPING_ADDRESS_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 1,
    'len' => 100,
    'size' => '20',
  ),
  'shipping_address' => 
  array (
    'required' => false,
    'name' => 'shipping_address',
    'vname' => 'LBL_SHIPPING_ADDRESS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_city' => 
  array (
    'required' => false,
    'name' => 'shipping_city',
    'vname' => 'LBL_SHIPPING_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'billing_county' => 
  array (
    'required' => false,
    'name' => 'billing_county',
    'vname' => 'LBL_BILLING_COUNTY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_county' => 
  array (
    'required' => false,
    'name' => 'shipping_county',
    'vname' => 'LBL_SHIPPING_COUNTY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_state' => 
  array (
    'required' => false,
    'name' => 'shipping_state',
    'vname' => 'LBL_SHIPPING_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_country' => 
  array (
    'required' => false,
    'name' => 'shipping_country',
    'vname' => 'LBL_SHIPPING_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
  'shipping_zip_code' => 
  array (
    'required' => false,
    'name' => 'shipping_zip_code',
    'vname' => 'LBL_SHIPPING_ZIP_CODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 1,
    'len' => '255',
    'size' => '20',
  ),
),
 'indices' => array (
        array('name' =>'order_id' , 'type'=>'unique' , 'fields'=>array('order_id')),

    ),

	'relationships'=>array (
	),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Orders','Orders', array('basic','team_security','assignable'));
