<?php
$mod_strings['LBL_RELATED_MODULES_PANEL_HELP_DESC'] = 'The primary module and all related modules appear here. Select a module.';
$mod_strings['LBL_CHART_DATA_HELP'] = 'Select the Summary that will be displayed in the chart';
$mod_strings['LBL_DO_ROUND_HELP'] = 'Un-check this box if you do not want large numbers to be rounded in charts';
$mod_strings['DEFAULT_REPORT_TITLE_43'] = 'Leads Generated By Campaign';
$mod_strings['DEFAULT_REPORT_TITLE_44'] = 'Closed Won Opportunity Info By Campaign';
$mod_strings['DEFAULT_REPORT_TITLE_45'] = 'Campaign By Name By Month By Status';
$mod_strings['DEFAULT_REPORT_TITLE_46'] = 'Campaign By Name By Month By Rating';
$mod_strings['DEFAULT_REPORT_TITLE_50'] = 'Closed Won Oppurtunity Info By Program';
$mod_strings['LBL_DO_ROUND'] = 'Enable Rounding';

?>