<?php
$viewdefs['pmse_Business_Rules']['base']['view']['dashlet-businessrules'] = array(
    'dashlets' => array(
        array(
            'label' => 'PMSE Business Rules',
            'description' => 'ProcessMaker Business Rules',
            'config' => array(
                'limit' => 10,
                'visibility' => 'user',
            ),
            'preview' => array(
                'limit' => 10,
                'visibility' => 'user',
            ),
            'filter' => array(
                'module' => array(
//                    'Accounts',
//                    'Bugs',
//                    'Cases',
//                    'Contacts',
                    'Home',
//                    'Leads',
//                    'Opportunities',
//                    'Prospects',
                    'pmse_Business_Rules',
//                    'pmse_BpmProcessDefinition',
                ),
                'view' => 'record',
            ),
        ),
    ),
    'custom_toolbar' => array(
        'buttons' => array(
            array(
                'type' => 'actiondropdown',
                'no_default_action' => true,
                'icon' => 'icon-plus',
                'buttons' => array(
                    array(
                        'type' => 'dashletaction',
                        'action' => 'createRecord',
                        'params' => array(
                            'module' => 'pmse_Business_Rules',
                            'link' => '#pmse_Business_Rules',
                        ),
                        'label' => 'Create Business Rules',
                        'acl_action' => 'create',
                        'acl_module' => 'pmse_Business_Rules',
                    ),
                    array(
                        'type' => 'dashletaction',
                        'action' => 'importRecord',
                        'params' => array(
                            'module' => 'pmse_Business_Rules',
                            'link' => '#pmse_Business_Rules/layout/businessrules-import'
                        ),
                        'label' => 'Import Business Rules',
//                        'acl_action' => 'importRecord',
                        'acl_module' => 'pmse_Business_Rules',
                    ),
                ),
            ),
            array(
                'dropdown_buttons' => array(
                    array(
                        'type' => 'dashletaction',
                        'action' => 'editClicked',
                        'label' => 'LBL_DASHLET_CONFIG_EDIT_LABEL',
                    ),
                    array(
                        'type' => 'dashletaction',
                        'action' => 'refreshClicked',
                        'label' => 'LBL_DASHLET_REFRESH_LABEL',
                    ),
//                    array(
//                        'type' => 'dashletaction',
//                        'action' => 'toggleClicked',
//                        'label' => 'LBL_DASHLET_MINIMIZE',
//                        'event' => 'minimize',
//                    ),
                    array(
                        'type' => 'dashletaction',
                        'action' => 'removeClicked',
                        'label' => 'LBL_DASHLET_REMOVE_LABEL',
                    ),
                ),
            ),
        ),
    ),

    'panels' => array(
        array(
            'name' => 'panel_body',
            'columns' => 2,
            'labelsOnTop' => true,
            'placeholders' => true,
            'fields' => array(
                array(
                    'name' => 'visibility',
                    'label' => 'LBL_DASHLET_CONFIGURE_MY_ITEMS_ONLY',
                    'type' => 'enum',
                    'options' => 'tasks_visibility_options',
                ),
                array(
                    'name' => 'limit',
                    'label' => 'LBL_DASHLET_CONFIGURE_DISPLAY_ROWS',
                    'type' => 'enum',
                    'options' => 'tasks_limit_options',
                ),
//                array(
//                    'name' => 'visibility',
//                    'label' => 'LBL_DASHLET_CONFIGURE_MY_ITEMS_ONLY',
//                    'type' => 'enum',
//                    'options' => 'tasks_visibility_options',
//                ),
//                array(
//                    'name' => 'limit',
//                    'label' => 'LBL_DASHLET_CONFIGURE_DISPLAY_ROWS',
//                    'type' => 'enum',
//                    'options' => 'tasks_limit_options',
//                ),
            ),
        ),
    ),
   /* 'tabs' => array(
        array(
            'active' => true,
            'filters' => array(
//                'prj_status' => array('$not_in' => array('INACTIVE')),
            ),
            'label' => 'LBL_PMSE_BUTTON_BUSINESSRULES',
            'link' => 'pmse_Business_Rules',
            'module' => 'pmse_Business_Rules',
            'order_by' => 'date_entered:asc',
            'record_date' => 'date_entered',
            'row_actions' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-edit',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:businessRulesLayout:fire',
                    'target' => 'view',
                    'tooltip' => 'Edit',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-remove',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:delete-record:fire',
                    'target' => 'view',
                    'tooltip' => 'Delete',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-download-alt',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:download:fire',
                    'target' => 'view',
                    'tooltip' => 'Export',
                    'acl_action' => 'edit',
                ),
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-eye-close',
//                    'css_class' => 'btn btn-mini',
//                    'event' => 'dashlet-processes:disable-record:fire',
//                    'target' => 'view',
//                    'tooltip' => 'Disable',
//                    'acl_action' => 'edit',
//                ),
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-info-sign',
//                    'css_class' => 'btn btn-mini',
//                    'event' => '',
//                    'target' => 'view',
//                    'tooltip' => 'Description',
//                    'acl_action' => 'edit',
//                ),
            ),
        ),
//        array(
//            'filters' => array(
//                'prj_status' => array('$not_in' => array('ACTIVE')),
//            ),
//            'label' => 'LBL_PMSE_BUTTON_DISABLE',
//            'link' => 'pmse_Project',
//            'module' => 'pmse_Project',
//            'order_by' => 'date_entered:asc',
//            'record_date' => 'date_entered',
//            'row_actions' => array(
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-edit',
//                    'css_class' => 'btn btn-mini',
//                    'event' => 'dessigner',
//                    'target' => 'view',
//                    'tooltip' => 'Designer',
//                    'acl_action' => 'edit',
//                ),
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-remove',
//                    'css_class' => 'btn btn-mini',
//                    'event' => '',
//                    'target' => 'view',
//                    'tooltip' => 'Delete',
//                    'acl_action' => 'edit',
//                ),
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-download-alt',
//                    'css_class' => 'btn btn-mini',
//                    'event' => '',
//                    'target' => 'view',
//                    'tooltip' => 'Export',
//                    'acl_action' => 'edit',
//                ),
//                array(
//                    'type' => 'rowaction',
//     icon               'icon' => 'icon-eye-open',
//                    'css_class' => 'btn btn-mini',
//                    'event' => 'dashlet-processes:enable-record:fire',
//                    'target' => 'view',
//                    'tooltip' => 'Enable',
//                    'acl_action' => 'edit',
//                ),
//                array(
//                    'type' => 'rowaction',
//                    'icon' => 'icon-info-sign',
//                    'css_class' => 'btn btn-mini',
//                    'event' => '',
//                    'target' => 'view',
//                    'tooltip' => 'Description',
//                    'acl_action' => 'edit',
//                ),
//            ),
//        ),
    ),*/


    'tabs' => array(
        array(
            'active' => true,
            'filters' => array(
                //'custom_source' => 'PMSE',
                //'cas_ownership' => array('$equals' => 'MYCASES'),
                'rst_type' => array('$not_in' => array('multiple')),
            ),
            'label' => 'Single Hit',
            'link' => 'pmse_Business_Rules',
            'module' => 'pmse_Business_Rules',
            'order_by' => 'date_entered:desc',
            'record_date' => 'date_entered',
            'row_actions' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-edit',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:businessRulesLayout:fire',
                    'target' => 'view',
                    'tooltip' => 'Edit',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-remove',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:delete-record:fire',
                    'target' => 'view',
                    'tooltip' => 'Delete',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-download-alt',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:download:fire',
                    'target' => 'view',
                    'tooltip' => 'Export',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-info-sign',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:description-record:fire',
                    'target' => 'view',
                    'tooltip' => 'Description',
                    'acl_action' => 'edit',
                ),
            ),
        ),
        array(
            'filters' => array(
                //'custom_source' => 'PMSE',
                //'cas_ownership' => array('$equals' => 'selfservice'),
                'rst_type' => array('$not_in' => array('single')),
            ),
            //'fields' => array('cas_id','cas_enrique'),
            'label' => 'Multiple Hit',
            'link' => 'pmse_Business_Rules',
            'module' => 'pmse_Business_Rules',
            'order_by' => 'date_entered:desc',
            'record_date' => 'date_entered',
            'row_actions' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-edit',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:businessRulesLayout:fire',
                    'target' => 'view',
                    'tooltip' => 'Edit',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-remove',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:delete-record:fire',
                    'target' => 'view',
                    'tooltip' => 'Delete',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-download-alt',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:download:fire',
                    'target' => 'view',
                    'tooltip' => 'Export',
                    'acl_action' => 'edit',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'icon-info-sign',
                    'css_class' => 'btn btn-mini',
                    'event' => 'dashlet-businessrules:description-record:fire',
                    'target' => 'view',
                    'tooltip' => 'Description',
                    'acl_action' => 'edit',
                ),
            ),
        ),
    ),
);