<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$result =  [
    'return' => [
        'companies' => [
            'firstHit' => '1',
            'hits' => '20',
            'lastHit' => '20',
            'totalHits' => '386',
            'hit' => [
                0 => [
                    'hitNumber' => '1',
                    'companyResults' => [
                        'companyId' => '10623000000000',
                        'duns' => '2205698',
                        'companyName' => 'Gannett Co., Inc.',
                        'locationType' => 'Headquarters',
                        'address1' => '7950 Jones Branch Dr.',
                        'city' => 'McLean',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'VA',
                        'primaryUrl' => 'http://www.gannett.com',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => '5438.678',
                        'hqPhone' => '703-854-6000',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                1 => [
                    'hitNumber' => '2',
                    'companyResults' => [
                        'companyId' => '120305000000000',
                        'duns' => '609153887',
                        'companyName' => 'Gannett Fleming, Inc.',
                        'locationType' => 'Headquarters',
                        'address1' => '207 Senate Ave.',
                        'city' => 'Camp Hill',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'PA',
                        'primaryUrl' => 'http://www.gannettfleming.com',
                        'parentDuns' => '28119915',
                        'ultimateParentDuns' => '28119915',
                        'sales' => '283.302',
                        'hqPhone' => '717-763-7211',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                2 => [
                    'hitNumber' => '3',
                    'companyResults' => [
                        'companyId' => '140922000000000',
                        'duns' => '2205698',
                        'companyName' => 'Gannett Media Technologies International',
                        'locationType' => '',
                        'address1' => '151 W. 4th St.',
                        'city' => 'Cincinnati',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'OH',
                        'primaryUrl' => 'http://www.gmti.com',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => null,
                        'hqPhone' => '513-665-3777',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                3 => [
                    'hitNumber' => '4',
                    'companyResults' => [
                        'companyId' => '238031301',
                        'duns' => '238031301',
                        'companyName' => 'GANNETT U.K. LTD',
                        'locationType' => 'Headquarters',
                        'address1' => '58 Church Street',
                        'city' => 'WEYBRIDGE',
                        'country' => 'England',
                        'countryId' => '245',
                        'stateOrProvince' => 'SURREY',
                        'primaryUrl' => '',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => '603.6081408',
                        'hqPhone' => '',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                4 => [
                    'hitNumber' => '5',
                    'companyResults' => [
                        'companyId' => '28119915',
                        'duns' => '28119915',
                        'companyName' => 'Gannett Fleming Affiliates, Inc',
                        'locationType' => 'Headquarters',
                        'address1' => '207 Senate Ave',
                        'city' => 'Camp Hill',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'PA',
                        'primaryUrl' => '',
                        'parentDuns' => '28119915',
                        'ultimateParentDuns' => '28119915',
                        'sales' => '285.298',
                        'hqPhone' => '717-763-7211',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                5 => [
                    'hitNumber' => '6',
                    'companyResults' => [
                        'companyId' => '14249759',
                        'duns' => '14249759',
                        'companyName' => 'GANNETT SATELLITE INFORMATION NETWORK, INC.',
                        'locationType' => 'Headquarters',
                        'address1' => '7950 Jones Branch Dr',
                        'city' => 'Mc Lean',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'VA',
                        'primaryUrl' => 'www.c-n.com',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => null,
                        'hqPhone' => '703-854-3400',
                        'dbas' => [
                            'dba' => 'USA Today',
                        ],
                        'historicalIndicator' => 'false',
                    ],
                ],
                6 => [
                    'hitNumber' => '7',
                    'companyResults' => [
                        'companyId' => '7133515',
                        'duns' => '7133515',
                        'companyName' => 'Gannett Missouri Publishing, Inc.',
                        'locationType' => 'Headquarters',
                        'address1' => '651 N Boonville Ave',
                        'city' => 'Springfield',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'MO',
                        'primaryUrl' => 'www.ozarksmarketplace.com',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => null,
                        'hqPhone' => '417-836-1100',
                        'dbas' => [
                            'dba' => [
                                0 => 'NEWS-LEADER ',
                                1 => ' SPRINGFIELD NEWS-LEADER',
                            ],
                        ],
                        'historicalIndicator' => 'false',
                    ],
                ],
                7 => [
                    'hitNumber' => '8',
                    'companyResults' => [
                        'companyId' => '6342026',
                        'duns' => '6342026',
                        'companyName' => 'Gannett River States Publishing Corporation',
                        'locationType' => 'Headquarters',
                        'address1' => '7950 Jones Branch Dr',
                        'city' => 'Mc Lean',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'VA',
                        'primaryUrl' => '',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => null,
                        'hqPhone' => '703-284-6000',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                8 => [
                    'hitNumber' => '9',
                    'companyResults' => [
                        'companyId' => '64204902',
                        'duns' => '64204902',
                        'companyName' => 'Gannett Fleming of Michigan Inc',
                        'locationType' => 'Headquarters',
                        'address1' => '207 Senate Ave',
                        'city' => 'Camp Hill',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'PA',
                        'primaryUrl' => '',
                        'parentDuns' => '609153887',
                        'ultimateParentDuns' => '28119915',
                        'sales' => null,
                        'hqPhone' => '717-763-7211',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                9 => [
                    'hitNumber' => '10',
                    'companyResults' => [
                        'companyId' => '81698342',
                        'duns' => '81698342',
                        'companyName' => 'GANNETT BROADCASTING INC',
                        'locationType' => 'Headquarters',
                        'address1' => '7950 Jones Branch Dr',
                        'city' => 'Mc Lean',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'VA',
                        'primaryUrl' => 'www.wxia.com',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => null,
                        'hqPhone' => '703-854-6000',
                        'dbas' => [
                            'dba' => 'Wxia-TV',
                        ],
                        'historicalIndicator' => 'false',
                    ],
                ],
                10 => [
                    'hitNumber' => '11',
                    'companyResults' => [
                        'companyId' => '135824808',
                        'duns' => '135824808',
                        'companyName' => 'Gannett Fleming Engineers and Architects, P.C.',
                        'locationType' => 'Headquarters',
                        'address1' => '209 Senate Ave Ste 100   #100',
                        'city' => 'Camp Hill',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'PA',
                        'primaryUrl' => '',
                        'parentDuns' => '135824808',
                        'ultimateParentDuns' => '135824808',
                        'sales' => null,
                        'hqPhone' => '717-763-7212',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                11 => [
                    'hitNumber' => '12',
                    'companyResults' => [
                        'companyId' => '840151794',
                        'duns' => '840151794',
                        'companyName' => 'Gannett Tile',
                        'locationType' => 'Single Location',
                        'address1' => '1030 Ne Churchill St',
                        'city' => 'Grants Pass',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'OR',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.14',
                        'hqPhone' => '541-761-3620',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                12 => [
                    'hitNumber' => '13',
                    'companyResults' => [
                        'companyId' => '800327681',
                        'duns' => '800327681',
                        'companyName' => 'The Gannett-Louisiana Charitable Projects Inc',
                        'locationType' => 'Single Location',
                        'address1' => '1201 3rd St',
                        'city' => 'Alexandria',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'LA',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.14',
                        'hqPhone' => '318-487-6423',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                13 => [
                    'hitNumber' => '14',
                    'companyResults' => [
                        'companyId' => '39913836',
                        'duns' => '39913836',
                        'companyName' => 'GANNETT HEALTHCARE GROUP',
                        'locationType' => 'Single Location',
                        'address1' => '11641 DAVENPORT RD',
                        'city' => 'LOS ALAMITOS',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'CA',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.084',
                        'hqPhone' => '562-596-1575',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                14 => [
                    'hitNumber' => '15',
                    'companyResults' => [
                        'companyId' => '56789589',
                        'duns' => '56789589',
                        'companyName' => 'GANNETT PACIFIC CORPORATION',
                        'locationType' => 'Single Location',
                        'address1' => '500 Ala Moana Blvd       #7500',
                        'city' => 'Honolulu',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'HI',
                        'primaryUrl' => 'www.gannett.com',
                        'parentDuns' => '2205698',
                        'ultimateParentDuns' => '2205698',
                        'sales' => '0.034081',
                        'hqPhone' => '',
                        'dbas' => [
                            'dba' => [
                                0 => 'BUY AND SELL ',
                                1 => ' Honolulu Advertiser ',
                                2 => ' PACIFIC MEDIA PUBLISHING ',
                                3 => ' PENNY SAVER',
                            ],
                        ],
                        'historicalIndicator' => 'false',
                    ],
                ],
                15 => [
                    'hitNumber' => '16',
                    'companyResults' => [
                        'companyId' => '31277630',
                        'duns' => '31277630',
                        'companyName' => 'Gannett Outdoor Marketing Inc',
                        'locationType' => 'Single Location',
                        'address1' => '45731 Harmony Ln',
                        'city' => 'Belleville',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'MI',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.1',
                        'hqPhone' => '734-697-8657',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                16 => [
                    'hitNumber' => '17',
                    'companyResults' => [
                        'companyId' => '54839217',
                        'duns' => '54839217',
                        'companyName' => 'G A Gannett LLC',
                        'locationType' => 'Single Location',
                        'address1' => '25 Norgate Rd',
                        'city' => 'Manhasset',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'NY',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.15',
                        'hqPhone' => '516-627-1660',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                17 => [
                    'hitNumber' => '18',
                    'companyResults' => [
                        'companyId' => '127839194',
                        'duns' => '127839194',
                        'companyName' => 'David G Gannett LLC',
                        'locationType' => 'Single Location',
                        'address1' => '1 SW Columbia St Ste 1850#1850',
                        'city' => 'Portland',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'OR',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.089',
                        'hqPhone' => '503-221-4477',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                18 => [
                    'hitNumber' => '19',
                    'companyResults' => [
                        'companyId' => '794948567',
                        'duns' => '794948567',
                        'companyName' => 'Gannett Peak Technical Services',
                        'locationType' => 'Single Location',
                        'address1' => '1918 Russell Ave',
                        'city' => 'Cheyenne',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'WY',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.5',
                        'hqPhone' => '307-287-0800',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
                19 => [
                    'hitNumber' => '20',
                    'companyResults' => [
                        'companyId' => '797749814',
                        'duns' => '797749814',
                        'companyName' => 'Gannett Offset',
                        'locationType' => 'Single Location',
                        'address1' => '444 N Michigan Ave       #200',
                        'city' => 'Chicago',
                        'country' => 'United States',
                        'countryId' => '76',
                        'stateOrProvince' => 'IL',
                        'primaryUrl' => '',
                        'parentDuns' => null,
                        'ultimateParentDuns' => null,
                        'sales' => '0.17',
                        'hqPhone' => '312-527-7700',
                        'dbas' => '',
                        'historicalIndicator' => 'false',
                    ],
                ],
            ],
        ],
    ],
];
