<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * Fix icons in custom header template for icons that were renamed in 7.6
 *
 * Since all icons were renamed in 7.6, usually with fa- prefix instead of icon-,
 * all prefixes should be updated. There are some icons that were renamed entirely.
 *
 * @see UIUX-1687 for related issues
 */
class SugarUpgradeFixIconNameChanges extends UpgradeScript
{
    public $order = 7420;
    public $type = self::UPGRADE_CUSTOM;

    public $labelPattern = '/icon-(plus|reorder|upload)/';
    public $foundPattern = false;
    /**
     * Icon replacements to change
     *
     * @var array
     */
    public $upgradeIcons = array(
        'icon-plus' => 'fa-plus',
        'icon-reorder' => 'fa-bars',
        'icon-upload' => 'fa-upload',
    );

    public function run()
    {
        if (version_compare($this->from_version, '7.0', '>') && version_compare($this->from_version, '7.6', '<')) {
            // only need to run this upgrading for greater than 7.0 and less than 7.7
            return;
        }
        foreach (glob('custom/modules/*/clients/base/menus/header/header.php') as $file) {
            $this->foundPattern = false;
            $viewdefs = null;
            include($file);
            if (!empty($viewdefs)) {
                $module = key($viewdefs);
                $array = $viewdefs[$module]['base']['menu']['header'];
                $this->fixIcons($array);
                if ($this->foundPattern) {
                    $this->log("Replacing old font awesome icons names in header: $file");
                    sugar_file_put_contents($file, "<?php\n\n/* This file was generated by the 7_FixIconNameChanges upgrader */\n\$viewdefs['{$module}']['base']['menu']['header'] =  " . var_export($array, true) . ";\n");
                }
            }
            $viewdefs = null;
        }
    }

    /**
     * loop over view, find icons that match pattern and replace them
     * @param array $arr
     */
    public function fixIcons(&$arr)
    {
        foreach ($arr as $key => $val) {
            if (is_array($val)) {
                $this->fixIcons($arr[$key]);
            } elseif ($key === 'icon' && preg_match($this->iconPattern, $val)) {
                $arr[$key] = $this->$upgradeIcons[$val];
                $this->foundPattern = true;
            }
        }
    }

}
