<?php
/*
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement ("MSA"), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2014 SugarCRM Inc.  All rights reserved.
 */

class SugarUpgradeRebuildActivitiesDashboards extends UpgradeScript
{
    public $order = 7550;
    public $type = self::UPGRADE_CUSTOM;

    public function run()
    {
        // The Activities dashlets changed in 7.2
        if (!version_compare($this->from_version, '7.2', '<')) {
            return;
        }

        // Array of what modules and what relationship names need to be converted
        $convertModules = array();

        // Look for history files, like the ones created by ActivitiesRelationship.php
        $historyFiles = glob("modules/*/clients/base/views/history/history.php");
        
        foreach ($historyFiles as $filename) {
            // Need to read the contents to check for a particular comment tag
            $contents = file_get_contents($filename);
            if (strpos($contents,"/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */") !== false) {
                // It's a match, actually load the file and use the built array to figure
                // out the relationship
                $coreDefs = array();
                $viewdefs = array();
                require($filename);
                
                // Convoluted, but where this data is available.
                $moduleName = $coreDefs['dashlets'][0]['filter']['module'][0];
                // buildClientFiles() automatically trims off the _meetings
                $relName = $coreDefs['tabs'][0]['link'];
                $convertModules[$moduleName] = $relName;
            }
        }

        // Grab files first, then process them so glob() doesn't ever freak out.
        foreach ($convertModules as $moduleName => $relName) {
            require_once('modules/ModuleBuilder/parsers/relationships/ActivitiesRelationship.php');
            $parser = new ActivitiesRelationship(array(
                                                     'for_activities' => true,
                                                     'is_custom' => true,
                                                     'relationship_name' => $relName,
                                                     'lhs_module' => $moduleName,
                                                     ));
            $newFiles = $parser->buildClientFiles($relName);
            
            foreach ($newFiles[$moduleName] as $filepart => $contents) {
                // history.php should be there, the other files might not be so lucky
                $filename = "modules/{$moduleName}/".$filepart;
                mkdir_recursive(dirname($filename));
                file_put_contents($filename, $contents);
            }
        }
        
    }
}
