<?php
/*
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement ("MSA"), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright  2004-2014 SugarCRM Inc.  All rights reserved.
 */
/**
 * Remove known smarty template labels in custom modules
 */
class SugarUpgradeUpdateCustomBrokenViewLabels extends UpgradeScript
{
    public $order = 7500;
    public $type = self::UPGRADE_CUSTOM;
    public $version = '7.2';

    public $labelPattern = '/\{\$MOD.(.*)|strip_semicolon/';
    public $foundPattern = false;

    public function run()
    {
        if (version_compare($this->from_version, '7.0', '<') || version_compare($this->from_version, '7.2', '>=')) {
            // only need to run this upgrading from 7.0 - 7.2
            return;
        }
        foreach (glob('custom/modules/*/clients/base/views/record/record.php') as $recordFile) {
            $this->foundPattern = false;
            $viewdef = null;
            include($recordFile);
            if (!empty($viewdefs)) {
                $module = key($viewdefs);
                $array = $viewdefs[$module]['base']['view']['record'];
                $this->fixLabels($array);
                if ($this->foundPattern) {
                    $this->log("Removing Smarty labels from file $recordFile");
                    sugar_file_put_contents($recordFile, "<?php\n\n/* This file was generated by the 7_UpdateCustomBrokenViewLabels upgrader */\n\$viewdefs['{$module}']['base']['view']['record'] =  " . var_export($array, true) . ";\n");
                }
            }
            $viewdefs = null;
        }
    }

    /**
     * loop over view, find labels that match pattern and remove them
     * @param array $arr
     */
    public function fixLabels(&$arr)
    {
        foreach ($arr as $key => $val) {
            if (is_array($val)) {
                $this->fixLabels($arr[$key]);
            } elseif ($key === 'label' && preg_match($this->labelPattern, $val)) {
                unset($arr[$key]);
                $this->foundPattern = true;
            }
        }
    }

}
