// $Id: drupal.js,v 1.29 2006/10/14 02:39:48 unconed Exp $
var Drupal=Drupal||{};Drupal.jsEnabled=document.getElementsByTagName&&document.createElement&&document.createTextNode&&document.documentElement&&document.getElementById;Drupal.extend=function(obj){for(var i in obj){if(this[i]){Drupal.extend.apply(this[i],[obj[i]]);}
else{this[i]=obj[i];}}};Drupal.redirectFormButton=function(uri,button,handler){button.onmouseover=button.onfocus=function(){button.onclick=function(){Drupal.createIframe();var button=this;var action=button.form.action;var target=button.form.target;this.form.action=uri;this.form.target='redirect-target';handler.onsubmit();window.iframeHandler=function(){var iframe=$('#redirect-target').get(0);button.form.action=action;button.form.target=target;try{response=(iframe.contentWindow||iframe.contentDocument||iframe).document.body.innerHTML;response=response.replace(/[\f\n\r\t]/g,' ');if(window.opera){response=response.replace(/&quot;/g,'"');}}
catch(e){response=null;}
response=Drupal.parseJson(response);if(response.status==0){handler.onerror(response.data);return;}
handler.oncomplete(response.data);return true;}
return true;}}
button.onmouseout=button.onblur=function(){button.onclick=null;}};Drupal.absolutePosition=function(el){var sLeft=0,sTop=0;var isDiv=/^div$/i.test(el.tagName);if(isDiv&&el.scrollLeft){sLeft=el.scrollLeft;}
if(isDiv&&el.scrollTop){sTop=el.scrollTop;}
var r={x:el.offsetLeft-sLeft,y:el.offsetTop-sTop};if(el.offsetParent){var tmp=Drupal.absolutePosition(el.offsetParent);r.x+=tmp.x;r.y+=tmp.y;}
return r;};Drupal.dimensions=function(el){return{width:el.offsetWidth,height:el.offsetHeight};};Drupal.mousePosition=function(e){return{x:e.clientX+document.documentElement.scrollLeft,y:e.clientY+document.documentElement.scrollTop};};Drupal.parseJson=function(data){if((data.substring(0,1)!='{')&&(data.substring(0,1)!='[')){return{status:0,data:data.length?data:'Unspecified error'};}
return eval('('+data+');');};Drupal.createIframe=function(){if($('#redirect-holder').size()){return;}
window.iframeHandler=function(){};var div=document.createElement('div');div.id='redirect-holder';$(div).html('<iframe name="redirect-target" id="redirect-target" class="redirect" onload="window.iframeHandler();"></iframe>');var iframe=div.firstChild;$(iframe).attr({name:'redirect-target',id:'redirect-target'}).css({position:'absolute',height:'1px',width:'1px',visibility:'hidden'});$('body').append(div);};Drupal.deleteIframe=function(){$('#redirect-holder').remove();};Drupal.freezeHeight=function(){Drupal.unfreezeHeight();var div=document.createElement('div');$(div).css({position:'absolute',top:'0px',left:'0px',width:'1px',height:$('body').css('height')}).attr('id','freeze-height');$('body').append(div);};Drupal.unfreezeHeight=function(){$('#freeze-height').remove();};Drupal.encodeURIComponent=function(item,uri){uri=uri||location.href;item=encodeURIComponent(item).replace('%2F','/');return uri.indexOf('?q=')?item:item.replace('%26','%2526').replace('%23','%2523');};if(Drupal.jsEnabled){document.documentElement.className='js';}