<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');


global $current_user,$dashletData;
include_once('custom/modules/Home/Dashlets/SLAcountdown/SLAcountdown.en_us.lang.php');

$dashletData['SLAcountdown']['searchFields'] = array('status'           => array('default' => array('New')),
                                                        'date_entered'     => array('default' => ''),
                                                        'date_modified'    => array('default' => ''),
                                                       	'assigned_user_id' => array('type'    => 'assigned_user_name',
                                                                                   'default' => ''),
                                                       	'team_id'          => array('default' => array('')),
                                                       );
$dashletData['SLAcountdown']['columns'] = array('case_number' => array('width' => '6',
                                                                          'label' => 'LBL_LIST_NUMBER',
                                                                          'default' => true,
                                                                          'sortable' => false,
                                                                          ),
                                                  'name' => array('width'   => '40',
                                                                  'label'   => 'LBL_LIST_SUBJECT',
                                                                  'link'    => true,
                                                                  'sortable' => false,
                                                                  'default' => true),
                                                  'account_name' => array('width' => '29',
                                                                         'label' => 'LBL_LIST_ACCOUNT_NAME',
                                                                         'sortable' => false,
                                                                         'link' => true,
                                                                         'id' => 'account_id',
                                                                         'default' => true),

                                                  'priority' => array('width'   => '15',
                                                  						'sortable' => false,
                                                                       'label'   => 'LBL_PRIORITY'),
                                                  'date_entered' => array('width'   => '15',
                                                  					'sortable' => false,
                                                                    'label'   => 'LBL_LIST_DATE_CREATED'),
                                                  'assigned_user_name' => array('width'   => '8',
								                                                  'sortable' => false,
								                                                  'default' => false,
                                                                                'label'   => 'LBL_LIST_ASSIGNED'),
                                                  'time_left' => array('width'   => '15',
                                                  							'sortable' => false,
                                                  							'default' => true,
                                                                          'label'   => $dashletStrings['SLAcountdown']['LBL_TIME_LEFT']),
                                                  'date_due' => array('width'   => '15',
                                                  							'sortable' => false,
                                                  							'default' => true,
                                                                          'label'   => $dashletStrings['SLAcountdown']['LBL_DATE_DUE']),


                                                  'team_name' => array('width'   => '15',
                                                  						'sortable' => false,
                                                                       'label'   => 'LBL_LIST_TEAM'),


                                                  );
$dashletData['SLAcountdown']['holidays'] = array(
                                                                                                        '2007-01-01' => 'New Years',
                                                                                                        '2007-02-19' => 'Presidents Day',
                                                                                                        '2007-05-28' => 'Memorial Day',
                                                                                                        '2007-07-04' => 'Forth of July',
                                                                                                        '2007-09-03' => 'Labor day',
                                                                                                        '2007-11-22' => 'Thanksgiving',
                                                                                                        '2007-11-23' => 'Thanksgiving',
                                                                                                        '2007-12-24' => 'Winter Break',
                                                                                                        '2007-12-25' => 'Winter Break',
                                                                                                        '2007-12-31' => 'New Years Eve',
                                                                                                        '2008-01-01' => 'New Years Day',
                                                                                                        '2008-02-18' => 'Presidents Day',
                                                                                                        '2008-05-26' => 'Memorial Day',
                                                                                                        '2008-07-04' => 'Independence Day',
                                                                                                        '2008-09-01' => 'Labor Day',
                                                                                                        '2008-11-27' => 'Thanksgiving',
                                                                                                        '2008-11-28' => 'Thanksgiving',
                                                                                                        '2008-12-24' => 'Christmas Eve',
                                                                                                        '2008-12-25' => 'Christmas Day',
													'2008-12-26' => 'Day After Christmas',
                                                                                                        '2008-12-31' => 'New Years Eve',
                                                                                                        '2009-01-01' => 'New Years Day',
													'2009-01-02' => 'Day After New Years',
                                                                                                        '2009-02-16' => 'Presidents Day',
                                                                                                        '2009-05-25' => 'Memorial Day',
                                                                                                        '2009-07-03' => 'Independence Day',
                                                                                                        '2009-09-07' => 'Labor Day',
                                                                                                        '2009-11-26' => 'Thanksgiving',
                                                                                                        '2009-11-27' => 'Thanksgiving',
                                                                                                        '2009-12-24' => 'Christmas Eve',
                                                                                                        '2009-12-25' => 'Christmas Day',
                                                                                                        '2009-12-31' => 'New Years Eve',
                                                                                                        '2010-01-01' => 'New Years Day',
					                                            			'2010-02-15' => 'Presidents Day',
                                                                                                        '2010-05-31' => 'Memorial Day',
                                                                                                        '2010-07-05' => 'Independence Day',
                                                                                                        '2010-09-06' => 'Labor Day',
                                                                                                        '2010-11-25' => 'Thanksgiving',
                                                                                                        '2010-11-26' => 'Thanksgiving',
                                                                                                        '2010-12-24' => 'Christmas Eve',
                                                                                                        '2010-12-27' => 'Christmas Day',
                                                                                                        '2010-12-31' => 'New Years Eve',
													);

// The key of the status field that represents "New";
$dashletData['SLAcountdown']['newStatus'] = 'New';
// Set the number of seconds to autoRefresh the dashlet
$dashletData['SLAcountdown']['autoRefresh'] = '300';
//SLA TIMES ARE IN MINUTES, Priority key must match the P1, P2, P3 area...SLA field keys must match premium, extended, legacy array
$dashletData['SLAcountdown']['sla'] = array(
                                                                                                'P1 System Down' => array(
                                                                                                        '' => '240',
                                                                                                        'premium' => '60',
                                                                                                        'Premium Support' => '60',
                                                                                                        'extended' => '120',
                                                                                                        'Extended Support' => '120',
                                                                                                        'Legacy Professional Support' => '120',
                                                                                                        'legacy_pro' => '120',
                                                                                                        'Standard Support' => '240',
                                                                                                        'standard' => '240',
                                                                                                        'partner_standard' => '240',
                                                                                                        'SugarCRM Partner' => '240',
                                                                                                        'Sugar Network' => '480',
                                                                                                        'Plug-in Support (Outlook or Word)' => '480',
													'outlook' => '480',
                                                                                                        'Open Source Support Pack I' => '480',
													'Open Source Support Pack II' => '480',
                                                                                                        'Open Source Single Incident' => '480',
                                                                                                        'os_pack_I' => '480',
                                                                                                        'os_pack_II' => '480',
                                                                                                        'os_single' => '480',
                                                                                                        'no_support' => '480',
                                                                                                        'NO SUPPORT PROVIDED' => '480',
													'Sugar Express' => '480',  // NASSI
                                                                                                ),
                                                                                                'P2 System Impaired' => array(
                                                                                                        '' => '720',
                                                                                                        'premium' => '120',
                                                                                                        'Premium Support' => '120',
                                                                                                        'extended' => '240',
                                                                                                        'Extended Support' => '240',
                                                                                                        'Legacy Professional Support' => '240',
                                                                                                        'legacy_pro' => '240',
                                                                                                        'Standard Support' => '720',
                                                                                                        'standard' => '720',
                                                                                                        'partner_standard' => '720',
                                                                                                        'SugarCRM Partner' => '720',
                                                                                                        'Sugar Network' => '720',
                                                                                                        'Plug-in Support (Outlook or Word)' => '720',
													'outlook' => '720',
                                                                                                        'Open Source Support Pack I' => '720',
													'Open Source Support Pack II' => '720',
                                                                                                        'Open Source Single Incident' => '720',
                                                                                                        'os_pack_I' => '720',
                                                                                                        'os_pack_II' => '720',
                                                                                                        'os_single' => '720',
                                                                                                        'no_support' => '720',
                                                                                                        'NO SUPPORT PROVIDED' => '720',
													'Sugar Express' => '720', // NASSI
                                                                                                ),                                                                                                        
                                                                                                'P3 General Issue' => array(
                                                                                                        '' => '1440',
                                                                                                        'premium' => '240',
                                                                                                        'Premium Support' => '240',
                                                                                                        'extended' => '720',
                                                                                                        'Extended Support' => '720',
                                                                                                        'Legacy Professional Support' => '720',
                                                                                                        'legacy_pro' => '720',
                                                                                                        'Standard Support' => '1440',
                                                                                                        'standard' => '1440',
                                                                                                        'partner_standard' => '1440',
                                                                                                        'SugarCRM Partner' => '1440',
                                                                                                        'Sugar Network' => '1440',
                                                                                                        'Plug-in Support (Outlook or Word)' => '1440',
													'outlook' => '1440',
                                                                                                        'Open Source Support Pack I' => '1440',
													'Open Source Support Pack II' => '1440',
                                                                                                        'Open Source Single Incident' => '1440',
                                                                                                        'os_pack_I' => '1440',
                                                                                                        'os_pack_II' => '1440',
                                                                                                        'os_single' => '1440',
                                                                                                        'no_support' => '1440',
                                                                                                        'NO SUPPORT PROVIDED' => '1440',
													'Sugar Express' => '1440', // NASSI
                                                                                                ),
                                                                                                '' => array(
                                                                                                        '' => '1440',
                                                                                                        'premium' => '240',
                                                                                                        'Premium Support' => '240',
                                                                                                        'extended' => '720',
                                                                                                        'Extended Support' => '720',
                                                                                                        'Legacy Professional Support' => '720',
                                                                                                        'legacy_pro' => '720',
                                                                                                        'Standard Support' => '1440',
                                                                                                        'standard' => '1440',
                                                                                                        'partner_standard' => '1440',
                                                                                                        'SugarCRM Partner' => '1440',
                                                                                                        'Sugar Network' => '1440',
													'Plug-in Support (Outlook or Word)' => '1440',
                                                                                                        'outlook' => '1440',
                                                                                                        'Open Source Support Pack I' => '1440',
                                                                                                        'Open Source Support Pack II' => '1440',
													'Open Source Single Incident' => '1440',
                                                                                                        'os_pack_I' => '1440',
                                                                                                        'os_pack_II' => '1440',
                                                                                                        'os_single' => '1440',
                                                                                                        'no_support' => '1440',
                                                                                                        'NO SUPPORT PROVIDED' => '1440',
													'Sugar Express' => '1440', // NASSI
                                                                                                ),
                                                                                        );     

?>
