<?php

$leadConvertMap = array(
	'assigned_user_id' => array('contacts' => 'assigned_user_id', 'accounts' => 'assigned_user_id', 'opportunities' => 'assigned_user_id'),
	'team_id' => array('contacts' => 'team_id', 'accounts' => 'team_id', 'opportunities' => 'team_id'),
	'salutation' => array('contacts' => 'salutation', 'accounts' => '', 'opportunities' => ''),
	'first_name' => array('contacts' => 'first_name', 'accounts' => '', 'opportunities' => ''),
	'last_name' => array('contacts' => 'last_name', 'accounts' => '', 'opportunities' => ''),
	'title' => array('contacts' => 'title', 'accounts' => '', 'opportunities' => ''),
	'lead_source' => array('contacts' => 'lead_source', 'accounts' => '', 'opportunities' => 'lead_source'),
	'department' => array('contacts' => 'department', 'accounts' => '', 'opportunities' => ''),
	'reports_to_id' => array('contacts' => 'reports_to_id', 'accounts' => '', 'opportunities' => ''),
	'do_not_call' => array('contacts' => 'do_not_call', 'accounts' => '', 'opportunities' => ''),
	'phone_home' => array('contacts' => 'phone_home', 'accounts' => '', 'opportunities' => ''),
	'phone_mobile' => array('contacts' => 'phone_mobile', 'accounts' => '', 'opportunities' => ''),
	'phone_work' => array('contacts' => 'phone_work', 'accounts' => 'phone_office', 'opportunities' => ''),
	'phone_other' => array('contacts' => 'phone_other', 'accounts' => 'phone_alternate', 'opportunities' => ''),
	'phone_fax' => array('contacts' => 'phone_fax', 'accounts' => 'phone_fax', 'opportunities' => ''),
	'email1' => array('contacts' => 'email1', 'accounts' => 'email1', 'opportunities' => ''),
	'email2' => array('contacts' => 'email2', 'accounts' => 'email2', 'opportunities' => ''),
	'email_opt_out' => array('contacts' => 'email_opt_out', 'accounts' => '', 'opportunities' => ''),
	'primary_address_street' => array('contacts' => 'primary_address_street', 'accounts' => 'billing_address_street', 'opportunities' => ''),
	'primary_address_city' => array('contacts' => 'primary_address_city', 'accounts' => 'billing_address_city', 'opportunities' => ''),
	'primary_address_state' => array('contacts' => 'primary_address_state', 'accounts' => 'billing_address_state', 'opportunities' => ''),
	'primary_address_postalcode' => array('contacts' => 'primary_address_postalcode', 'accounts' => 'billing_address_postalcode', 'opportunities' => ''),
	'primary_address_country' => array('contacts' => 'primary_address_country', 'accounts' => 'billing_address_country', 'opportunities' => ''),
	'alt_address_street' => array('contacts' => 'alt_address_street', 'accounts' => 'shipping_address_street', 'opportunities' => ''),
	'alt_address_city' => array('contacts' => 'alt_address_city', 'accounts' => 'shipping_address_city', 'opportunities' => ''),
	'alt_address_state' => array('contacts' => 'alt_address_state', 'accounts' => 'shipping_address_state', 'opportunities' => ''),
	'alt_address_postalcode' => array('contacts' => 'alt_address_postalcode', 'accounts' => 'shipping_address_postalcode', 'opportunities' => ''),
	'alt_address_country' => array('contacts' => 'alt_address_country', 'accounts' => 'shipping_address_country', 'opportunities' => ''),
	'description' => array('contacts' => 'description', 'accounts' => 'description', 'opportunities' => 'description'),
	'account_name' => array('contacts' => '', 'accounts' => 'name', 'opportunities' => ''),
	'portal_name' => array('contacts' => 'portal_name', 'accounts' => '', 'opportunities' => ''),
	'portal_app' => array('contacts' => 'portal_app', 'accounts' => '', 'opportunities' => ''),
	'invalid_email' => array('contacts' => 'invalid_email', 'accounts' => '', 'opportunities' => ''),
	'assistant' => array('contacts' => 'assistant', 'accounts' => '', 'opportunities' => ''),
	'assistant_phone' => array('contacts' => 'assistant_phone', 'accounts' => '', 'opportunities' => ''),
	'campaign_name' => array('contacts' => '', 'accounts' => 'campaign_id', 'opportunities' => 'campaign_id'),
	'sic_code_c' => array('contacts' => '', 'accounts' => 'sic_code', 'opportunities' => ''),
	'website_c' => array('contacts' => '', 'accounts' => 'website', 'opportunities' => ''),
	'industry' => array('contacts' => '', 'accounts' => 'industry', 'opportunities' => ''),
	'annual_revenue2_c' => array('contacts' => '', 'accounts' => 'annual_revenue', 'opportunities' => ''),
	'employee_qty_c' => array('contacts' => '', 'accounts' => 'employees', 'opportunities' => ''),
	'competitor_1' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'competitor_1'),
	'competitor_2' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'competitor_2'),
	'competitor_3' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'competitor_3'),
	'lead_type' => array('contacts' => '', 'accounts' => 'account_type', 'opportunities' => ''),
	'current_solution' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'current_solution'),
	'website_c' => array('contacts' => '', 'accounts' => 'website', 'opportunities' => ''),
	'next_step_c' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'next_step'),
	'next_step_due_date_c' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'next_step_due_date'),
	'lead_owner_c' => array('contacts' => '', 'accounts' => '', 'opportunities' => 'associated_rep_c'),
);

?>
