<?php

$touchpointsScrubMap = array(
	'description' => array(
		'Interaction' => 'description',
		'LeadContact' => 'description',
		'LeadAccount' => 'description',
		'Contact' => 'description',
		'Account' => 'description',
	),
	'assigned_user_id' => array(
		'Interaction' => '',
		'LeadContact' => 'assigned_user_id',
		'LeadAccount' => 'assigned_user_id',
		'Contact' => 'assigned_user_id',
		'Account' => 'assigned_user_id',
	),
	'team_id' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'first_name' => array(
		'Interaction' => 'first_name',
		'LeadContact' => 'first_name',
		'LeadAccount' => '',
		'Contact' => 'first_name',
		'Account' => '',
	),
	'last_name' => array(
		'Interaction' => 'last_name',
		'LeadContact' => 'last_name',
		'LeadAccount' => '',
		'Contact' => 'last_name',
		'Account' => '',
	),
	'primary_address_country' => array(
		'Interaction' => '',
		'LeadContact' => 'primary_address_country',
		'LeadAccount' => 'billing_address_country',
		'Contact' => 'primary_address_country',
		'Account' => 'billing_address_country',
	),
	'primary_address_street' => array(
		'Interaction' => '',
		'LeadContact' => 'primary_address_street',
		'LeadAccount' => 'billing_address_street',
		'Contact' => 'primary_address_street',
		'Account' => 'billing_address_street',
	),
	'primary_address_city' => array(
		'Interaction' => '',
		'LeadContact' => 'primary_address_city',
		'LeadAccount' => 'billing_address_city',
		'Contact' => 'primary_address_city',
		'Account' => 'billing_address_city',
	),
	'primary_address_state' => array(
		'Interaction' => '',
		'LeadContact' => 'primary_address_state',
		'LeadAccount' => 'billing_address_state',
		'Contact' => 'primary_address_state',
		'Account' => 'billing_address_state',
	),
	'primary_address_postalcode' => array(
		'Interaction' => '',
		'LeadContact' => 'primary_address_postalcode',
		'LeadAccount' => 'billing_address_postalcode',
		'Contact' => 'primary_address_postalcode',
		'Account' => 'billing_address_postalcode',
	),
	'alt_address_country' => array(
		'Interaction' => '',
		'LeadContact' => 'alt_address_country',
		'LeadAccount' => 'shipping_address_country',
		'Contact' => 'alt_address_country',
		'Account' => 'shipping_address_country',
	),
	'alt_address_street' => array(
		'Interaction' => '',
		'LeadContact' => 'alt_address_street',
		'LeadAccount' => 'shipping_address_street',
		'Contact' => 'alt_address_street',
		'Account' => 'shipping_address_street',
	),
	'alt_address_city' => array(
		'Interaction' => '',
		'LeadContact' => 'alt_address_city',
		'LeadAccount' => 'shipping_address_city',
		'Contact' => 'alt_address_city',
		'Account' => 'shipping_address_city',
	),
	'alt_address_state' => array(
		'Interaction' => '',
		'LeadContact' => 'alt_address_state',
		'LeadAccount' => 'shipping_address_state',
		'Contact' => 'alt_address_state',
		'Account' => 'shipping_address_state',
	),
	'alt_address_postalcode' => array(
		'Interaction' => '',
		'LeadContact' => 'alt_address_postalcode',
		'LeadAccount' => 'shipping_address_postalcode',
		'Contact' => 'alt_address_postalcode',
		'Account' => 'shipping_address_postalcode',
	),
	'purchasing_timeline' => array(
		'Interaction' => '',
		'LeadContact' => 'purchasing_timeline_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'title' => array(
		'Interaction' => '',
		'LeadContact' => 'title',
		'LeadAccount' => '',
		'Contact' => 'title',
		'Account' => '',
	),
	'source_type' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'score' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'scrub_result' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'scrub_relation_type' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'scrubbed' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'email1' => array(
		'Interaction' => '',
		'LeadContact' => 'email1',
		'LeadAccount' => '',
		'Contact' => 'email1',
		'Account' => '',
	),
	'portal_name' => array(
		'Interaction' => '',
		'LeadContact' => 'portal_name',
		'LeadAccount' => '',
		'Contact' => 'portal_name',
		'Account' => '',
	),
	'discrepancies' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'campaign_id' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'new_leadaccount_id' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'new_leadcontact_id' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'lead_source' => array(
		'Interaction' => 'lead_source',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'lead_group' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'lead_group_c',
		'Contact' => '',
		'Account' => '',
	),
	'industry' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'industry',
		'Contact' => '',
		'Account' => 'industry',
	),
	'annual_revenue' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'annual_revenue',
		'Contact' => '',
		'Account' => 'annual_revenue',
	),
	'phone_fax' => array(
		'Interaction' => '',
		'LeadContact' => 'phone_fax',
		'LeadAccount' => 'phone_fax',
		'Contact' => 'phone_fax',
		'Account' => 'phone_fax',
	),
	'phone_home' => array(
		'Interaction' => '',
		'LeadContact' => 'phone_home',
		'LeadAccount' => '',
		'Contact' => 'phone_home',
		'Account' => '',
	),
	'phone_mobile' => array(
		'Interaction' => '',
		'LeadContact' => 'phone_mobile',
		'LeadAccount' => '',
		'Contact' => 'phone_mobile',
		'Account' => '',
	),
	'phone_work' => array(
		'Interaction' => '',
		'LeadContact' => 'phone_work',
		'LeadAccount' => '',
		'Contact' => 'phone_work',
		'Account' => '',
	),
	'phone_other' => array(
		'Interaction' => '',
		'LeadContact' => 'phone_other',
		'LeadAccount' => '',
		'Contact' => 'phone_other',
		'Account' => '',
	),
	'phone_office' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'phone_office',
		'Contact' => '',
		'Account' => 'phone_office',
	),
	'phone_alternate' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'phone_alternate',
		'Contact' => '',
		'Account' => 'phone_alternate',
	),
	'website' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'website',
		'Contact' => '',
		'Account' => 'website',
	),
	'ownership' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'ownership',
		'Contact' => '',
		'Account' => 'ownership',
	),
	'employees' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'employees',
		'Contact' => '',
		'Account' => 'employees',
	),
	'ticker_symbol' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'ticker_symbol',
		'Contact' => '',
		'Account' => 'ticker_symbol',
	),
	'referred_by' => array(
		'Interaction' => 'referred_by',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'conversion_date' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'salutation' => array(
		'Interaction' => '',
		'LeadContact' => 'salutation',
		'LeadAccount' => '',
		'Contact' => 'salutation',
		'Account' => '',
	),
	'department' => array(
		'Interaction' => '',
		'LeadContact' => 'department',
		'LeadAccount' => '',
		'Contact' => 'department',
		'Account' => '',
	),
	'do_not_call' => array(
		'Interaction' => '',
		'LeadContact' => 'do_not_call',
		'LeadAccount' => '',
		'Contact' => 'do_not_call',
		'Account' => '',
	),
	'company_name' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'name',
		'Contact' => '',
		'Account' => 'name',
	),
	'email_opt_out' => array(
		'Interaction' => '',
		'LeadContact' => 'email_opt_out',
		'LeadAccount' => 'email_opt_out',
		'Contact' => 'email_opt_out',
		'Account' => 'email_opt_out',
	),
	'how_they_heard' => array(
		'Interaction' => '',
		'LeadContact' => 'how_they_heard_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'current_solution' => array(
		'Interaction' => '',
		'LeadContact' => 'current_solution_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'replace_timeline' => array(
		'Interaction' => '',
		'LeadContact' => 'replace_timeline_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'products_of_interest' => array(
		'Interaction' => '',
		'LeadContact' => 'products_of_interest_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'years_selling_crm' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'years_selling_crm',
		'Contact' => '',
		'Account' => '',
	),
	'open_source_exp' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'open_source_exp',
		'Contact' => '',
		'Account' => '',
	),
	'gross_annual_sales' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'gross_annual_sales',
		'Contact' => '',
		'Account' => '',
	),
	'vertical_markets_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'vertical_markets_c',
		'Contact' => '',
		'Account' => '',
	),
	'area_of_expertise' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'area_of_expertise',
		'Contact' => '',
		'Account' => '',
	),
	'back_office_support' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'back_office_support',
		'Contact' => '',
		'Account' => '',
	),
	'regions_covered' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'regions_covered',
		'Contact' => '',
		'Account' => '',
	),
	'software_resell' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'software_resell',
		'Contact' => '',
		'Account' => '',
	),
	'hosting_servers' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'hosting_servers',
		'Contact' => '',
		'Account' => '',
	),
	'partner_assigned_to' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'partner_assigned_to',
		'Contact' => '',
		'Account' => '',
	),
	'budget_c' => array(
		'Interaction' => '',
		'LeadContact' => 'budget_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'competitor_1' => array(
		'Interaction' => '',
		'LeadContact' => 'competitor_1_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'competitor_2' => array(
		'Interaction' => '',
		'LeadContact' => 'competitor_2_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'competitor_3' => array(
		'Interaction' => '',
		'LeadContact' => 'competitor_3_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'operating_system' => array(
		'Interaction' => '',
		'LeadContact' => 'operating_system_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'remote_ip_address_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'remote_ip_address_c',
		'Contact' => '',
		'Account' => '',
	),
	'call_back_c' => array(
		'Interaction' => '',
		'LeadContact' => 'call_back_c',
		'LeadAccount' => 'call_back_c',
		'Contact' => '',
		'Account' => '',
	),
	'potential_users_c' => array(
		'Interaction' => '',
		'LeadContact' => 'potential_users_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'region_c' => array(
		'Interaction' => '',
		'LeadContact' => 'region_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => 'region_c',
	),
	'lead_group_c' => array(
		'Interaction' => '',
		'LeadContact' => 'lead_group_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	're_assignment_qty_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 're_assignment_qty_c',
		'Contact' => '',
		'Account' => '',
	),
	'initial_subscriptions_c' => array(
		'Interaction' => '',
		'LeadContact' => 'initial_subscriptions_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'third_party_validation_c' => array(
		'Interaction' => '',
		'LeadContact' => 'third_party_validation_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'registered_eval_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'registered_eval_c',
		'Contact' => '',
		'Account' => '',
	),
	'decision_date_c' => array(
		'Interaction' => '',
		'LeadContact' => 'decision_date_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'usage_groups_c' => array(
		'Interaction' => '',
		'LeadContact' => 'usage_groups_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'lead_pass_c' => array(
		'Interaction' => '',
		'LeadContact' => 'lead_pass_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'instance_key_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'instance_key_c',
		'Contact' => '',
		'Account' => '',
	),
	'lead_pass_date_c' => array(
		'Interaction' => '',
		'LeadContact' => 'lead_pass_date_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
	'next_step_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'next_step_c',
		'Contact' => '',
		'Account' => '',
	),
	'next_step_due_date_c' => array(
		'Interaction' => '',
		'LeadContact' => '',
		'LeadAccount' => 'next_step_due_date_c',
		'Contact' => '',
		'Account' => '',
	),
	'partner_assigned_to_c' => array(
		'Interaction' => '',
		'LeadContact' => 'partner_assigned_to_c',
		'LeadAccount' => '',
		'Contact' => '',
		'Account' => '',
	),
//** BEGIN CUSTOMIZATION EDDY IT TIX 12706
        'score' => array(
                'Interaction' => 'score',
                'LeadContact' => 'score',
                'LeadAccount' => 'score',
                'Contact' => 'score_c',
                'Account' => 'score_c',
        ),
        'prospect_id_c' => array(
                'Interaction' => '',
                'LeadContact' => 'prospect_id_c',
                'LeadAccount' => '',
                'Contact' => 'prospect_id_c',
                'Account' => '',
        ),

//** END CUSTOMIZATION EDDY IT TIX 12706

);

