<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Enterprise Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/products/sugar-enterprise-eula.html
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2010 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
$dictionary['P1_Partners'] = array(
  'table' => 'opportunities',
  'audited' => true,
  'comment' => 'An opportunity is the target of selling activities',
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_OPPORTUNITY_NAME',
      'type' => 'name',
      'dbType' => 'varchar',
      'len' => '50',
      'unified_search' => true,
      'comment' => 'Name of the opportunity',
      'merge_filter' => 'selected',
      'importable' => 'required',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED_ID',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED_ID',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
    ),
     'partner_assigned_to_name' => 
    array (
      'name' => 'partner_assigned_to_name',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'varchar',
      'source' => 'non-db',
       'len' => '25',
    ),
    
    
    
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'opportunities_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'opportunities_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'opportunities_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'team_id' => 
    array (
      'name' => 'team_id',
      'vname' => 'LBL_TEAM_ID',
      'group' => 'team_name',
      'reportable' => false,
      'dbType' => 'id',
      'type' => 'team_list',
      'audited' => true,
      'comment' => 'Team ID for the account',
    ),
    'team_set_id' => 
    array (
      'name' => 'team_set_id',
      'rname' => 'id',
      'id_name' => 'team_set_id',
      'vname' => 'LBL_TEAM_SET_ID',
      'type' => 'id',
      'audited' => true,
      'studio' => 'false',
    ),
    'team_count' => 
    array (
      'name' => 'team_count',
      'rname' => 'team_count',
      'id_name' => 'team_id',
      'vname' => 'LBL_TEAMS',
      'join_name' => 'ts1',
      'table' => 'teams',
      'type' => 'relate',
      'required' => 'true',
      'isnull' => 'true',
      'module' => 'Teams',
      'link' => 'team_count_link',
      'massupdate' => false,
      'dbType' => 'int',
      'source' => 'non-db',
      'importable' => 'false',
      'reportable' => false,
      'duplicate_merge' => 'disabled',
      'studio' => 'false',
    ),
    'team_name' => 
    array (
      'name' => 'team_name',
      'db_concat_fields' => 
      array (
        0 => 'name',
        1 => 'name_2',
      ),
      'rname' => 'name',
      'id_name' => 'team_id',
      'vname' => 'LBL_TEAMS',
      'type' => 'relate',
      'required' => 'true',
      'table' => 'teams',
      'isnull' => 'true',
      'module' => 'Teams',
      'link' => 'team_link',
      'massupdate' => false,
      'dbType' => 'varchar',
      'source' => 'non-db',
      'len' => 36,
      'custom_type' => 'teamset',
    ),
    'team_link' => 
    array (
      'name' => 'team_link',
      'type' => 'link',
      'relationship' => 'opportunities_team',
      'vname' => 'LBL_TEAMS_LINK',
      'link_type' => 'one',
      'module' => 'Teams',
      'bean_name' => 'Team',
      'source' => 'non-db',
      'duplicate_merge' => 'disabled',
      'studio' => 'false',
    ),
    'team_count_link' => 
    array (
      'name' => 'team_count_link',
      'type' => 'link',
      'relationship' => 'opportunities_team_count_relationship',
      'link_type' => 'one',
      'module' => 'Teams',
      'bean_name' => 'TeamSet',
      'source' => 'non-db',
      'duplicate_merge' => 'disabled',
      'reportable' => false,
      'studio' => 'false',
    ),
    'teams' => 
    array (
      'name' => 'teams',
      'type' => 'link',
      'relationship' => 'opportunities_teams',
      'bean_filter_field' => 'team_set_id',
      'rhs_key_override' => true,
      'source' => 'non-db',
      'vname' => 'LBL_TEAMS',
      'link_class' => 'TeamSetLink',
      'link_file' => 'modules/Teams/TeamSetLink.php',
      'studio' => 'false',
      'reportable' => false,
    ),
    'opportunity_type' => 
    array (
      'name' => 'opportunity_type',
      'vname' => 'LBL_TYPE',
      'type' => 'enum',
      'options' => 'opportunity_type_dom',
      'len' => '255',
      'audited' => true,
      'comment' => 'Type of opportunity (ex: Existing, New)',
      'merge_filter' => 'enabled',
      'required' => '1',
      'source' => 'custom_fields',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'reportable' => 1,
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesopportunity_type',
      'custom_module' => 'Opportunities',
    ),
    
    'account_name' => 
    array (
      'name' => 'account_name',
      'rname' => 'name',
      'id_name' => 'account_id',
      'vname' => 'LBL_ACCOUNT_NAME',
      'type' => 'relate',
      'table' => 'accounts',
      'join_name' => 'accounts',
      'isnull' => 'true',
      'module' => 'Accounts',
      'dbType' => 'varchar',
      'link' => 'accounts',
      'len' => '255',
      'source' => 'non-db',
      'unified_search' => true,
      'required' => true,
      'importable' => 'required',
    ),
    'account_id' => 
    array (
      'name' => 'account_id',
      'vname' => 'LBL_ACCOUNT_ID',
      'type' => 'id',
      'source' => 'non-db',
      'audited' => true,
    ),
    
	'account_billing_country' => 
    array (
      'name' => 'account_billing_country',
      'rname' => 'billing_address_country',
      'vname' => 'LBL_ACCOUNT_BILLING_COUNTRY',
      'type' => 'varchar',
      'source' => 'non-db',
      'audited' => true,
    ),
    //Support for link to partner account
   "accounts_opportunities_1_name" => array (
	  'name' => 'accounts_opportunities_1_name',
	  'type' => 'relate',
	  'source' => 'non-db',
	  'vname' => 'LBL_ACCOUNTS_OPPORTUNITIES_1_FROM_ACCOUNTS_TITLE',
	  'save' => true,
	  'id_name' => 'accounts_o2772ccounts_ida',
	  'link' => 'accounts_opportunities_1',
	  'table' => 'accounts',
	  'module' => 'Accounts',
	  'rname' => 'name',
),

"accounts_o2772ccounts_ida" => array (
	'name' => 'accounts_o2772ccounts_ida',
	'type' => 'link',
	'relationship' => 'accounts_opportunities_1',
	'source' => 'non-db',
	'side' => 'right',
	'vname' => 'LBL_ACCOUNTS_OPPORTUNITIES_1_FROM_ACCOUNTS_TITLE',
),

"accounts_opportunities_1" => array (
	'name' => 'accounts_opportunities_1',
	'type' => 'link',
	'relationship' => 'accounts_opportunities_1',
	'source' => 'non-db',
	'side' => 'right',
	'vname' => 'LBL_ACCOUNTS_OPPORTUNITIES_1_FROM_ACCOUNTS_TITLE',
),
    
"opportunities_accounts" => array (
	  'name' => 'opportunities_accounts',
	  'type' => 'link',
	  'relationship' => 'opportunities_accounts',
	  'source' => 'non-db',
  ),
    
    'campaign_id' => 
    array (
      'name' => 'campaign_id',
      'comment' => 'Campaign that generated lead',
      'vname' => 'LBL_CAMPAIGN_ID',
      'rname' => 'id',
      'type' => 'id',
      'dbType' => 'id',
      'table' => 'campaigns',
      'isnull' => 'true',
      'module' => 'Campaigns',
      'reportable' => false,
      'massupdate' => false,
      'duplicate_merge' => 'disabled',
    ),
    'campaign_name' => 
    array (
      'name' => 'campaign_name',
      'rname' => 'name',
      'id_name' => 'campaign_id',
      'vname' => 'LBL_CAMPAIGN',
      'type' => 'relate',
      'link' => 'campaign_opportunities',
      'isnull' => 'true',
      'table' => 'campaigns',
      'module' => 'Campaigns',
      'source' => 'non-db',
    ),
    'campaign_opportunities' => 
    array (
      'name' => 'campaign_opportunities',
      'type' => 'link',
      'vname' => 'LBL_CAMPAIGN_OPPORTUNITY',
      'relationship' => 'campaign_opportunities',
      'source' => 'non-db',
    ),
    'lead_source' => 
    array (
      'name' => 'lead_source',
      'vname' => 'LBL_LEAD_SOURCE',
      'type' => 'enum',
      'options' => 'lead_source_dom',
      'len' => '50',
      'comment' => 'Source of the opportunity',
      'merge_filter' => 'enabled',
    ),
    'amount' => 
    array (
      'name' => 'amount',
      'vname' => 'LBL_AMOUNT',
      'type' => 'currency',
      'dbType' => 'double',
      'comment' => 'Unconverted amount of the opportunity',
      'duplicate_merge' => 'disabled',
      'importable' => 'required',
    ),
    'amount_usdollar' => 
    array (
      'name' => 'amount_usdollar',
      'vname' => 'LBL_AMOUNT_USDOLLAR',
      'type' => 'currency',
      'group' => 'amount',
      'dbType' => 'double',
      'disable_num_format' => true,
      'audited' => true,
      'comment' => 'Formatted amount of the opportunity',
    ),
    'currency_id' => 
    array (
      'name' => 'currency_id',
      'type' => 'id',
      'group' => 'currency_id',
      'vname' => 'LBL_CURRENCY_ID',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
      'reportable' => false,
      'comment' => 'Currency used for display purposes',
    ),
    'currency_name' => 
    array (
      'name' => 'currency_name',
      'rname' => 'name',
      'id_name' => 'currency_id',
      'vname' => 'LBL_CURRENCY_NAME',
      'type' => 'relate',
      'isnull' => 'true',
      'table' => 'currencies',
      'module' => 'Currencies',
      'source' => 'non-db',
      'function' => 
      array (
        'name' => 'getCurrencyNameDropDown',
        'returns' => 'html',
      ),
      'studio' => 'false',
    ),
    'currency_symbol' => 
    array (
      'name' => 'currency_symbol',
      'rname' => 'symbol',
      'id_name' => 'currency_id',
      'vname' => 'LBL_CURRENCY_SYMBOL',
      'type' => 'relate',
      'isnull' => 'true',
      'table' => 'currencies',
      'module' => 'Currencies',
      'source' => 'non-db',
      'function' => 
      array (
        'name' => 'getCurrencySymbolDropDown',
        'returns' => 'html',
      ),
    ),
    'date_closed' => 
    array (
      'name' => 'date_closed',
      'vname' => 'LBL_DATE_CLOSED',
      'type' => 'date',
      'audited' => true,
      'comment' => 'Expected or actual date the oppportunity will close',
      'importable' => 'required',
    ),
    'next_step' => 
    array (
      'name' => 'next_step',
      'vname' => 'LBL_NEXT_STEP',
      'type' => 'varchar',
      'len' => '255',
      'comment' => 'The next step in the sales process',
      'merge_filter' => 'enabled',
    ),
    'sales_stage' => 
    array (
      'name' => 'sales_stage',
      'vname' => 'LBL_SALES_STAGE',
      'type' => 'enum',
      'options' => 'sales_stage_dom',
      'len' => '25',
      'audited' => true,
      'comment' => 'Indication of progression towards closure',
      'merge_filter' => 'enabled',
      'importable' => 'required',
    ),
    'probability' => 
    array (
      'name' => 'probability',
      'vname' => 'LBL_PROBABILITY',
      'type' => 'int',
      'dbType' => 'double',
      'audited' => true,
      'comment' => 'The probability of closure',
      'validation' => 
      array (
        'type' => 'range',
        'min' => 0,
        'max' => 100,
      ),
      'merge_filter' => 'enabled',
    ),
    'accounts' => 
    array (
      'name' => 'accounts',
      'type' => 'link',
      'relationship' => 'accounts_opportunities',
      'source' => 'non-db',
      'link_type' => 'one',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_ACCOUNTS',
    ),
    'contacts' => 
    array (
      'name' => 'contacts',
      'type' => 'link',
      'relationship' => 'opportunities_contacts',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'rel_fields' => 
      array (
        'contact_role' => 
        array (
          'type' => 'enum',
          'options' => 'opportunity_relationship_type_dom',
        ),
      ),
      'vname' => 'LBL_CONTACTS',
    ),
    'tasks' => 
    array (
      'name' => 'tasks',
      'type' => 'link',
      'relationship' => 'opportunity_tasks',
      'source' => 'non-db',
      'vname' => 'LBL_TASKS',
    ),
    'notes' => 
    array (
      'name' => 'notes',
      'type' => 'link',
      'relationship' => 'opportunity_notes',
      'source' => 'non-db',
      'vname' => 'LBL_NOTES',
    ),
    'meetings' => 
    array (
      'name' => 'meetings',
      'type' => 'link',
      'relationship' => 'opportunity_meetings',
      'source' => 'non-db',
      'vname' => 'LBL_MEETINGS',
    ),
    'calls' => 
    array (
      'name' => 'calls',
      'type' => 'link',
      'relationship' => 'opportunity_calls',
      'source' => 'non-db',
      'vname' => 'LBL_CALLS',
    ),
    'emails' => 
    array (
      'name' => 'emails',
      'type' => 'link',
      'relationship' => 'emails_opportunities_rel',
      'source' => 'non-db',
      'vname' => 'LBL_EMAILS',
    ),
    'quotes' => 
    array (
      'name' => 'quotes',
      'type' => 'link',
      'relationship' => 'quotes_opportunities',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTES',
    ),
    'project' => 
    array (
      'name' => 'project',
      'type' => 'link',
      'relationship' => 'projects_opportunities',
      'source' => 'non-db',
      'vname' => 'LBL_PROJECTS',
    ),
    'leadaccounts' => 
    array (
      'name' => 'leadaccounts',
      'type' => 'link',
      'relationship' => 'p1_opportunity_leadaccounts',
      'source' => 'non-db',
      'vname' => 'LBL_LEADACCOUNTS',
    ),
    'leadcontacts' => 
    array (
      'name' => 'leadcontacts',
      'type' => 'link',
      'relationship' => 'opportunity_leadcontacts',
      'source' => 'non-db',
      'vname' => 'LBL_LEADCONTACTS',
    ),
    'campaigns' => 
    array (
      'name' => 'campaigns',
      'type' => 'link',
      'relationship' => 'opportunities_campaign',
      'module' => 'CampaignLog',
      'bean_name' => 'CampaignLog',
      'source' => 'non-db',
      'vname' => 'LBL_CAMPAIGNS',
    ),
    'campaign_link' => 
    array (
      'name' => 'campaign_link',
      'type' => 'link',
      'relationship' => 'opportunities_campaign',
      'vname' => 'LBL_CAMPAIGNS',
      'link_type' => 'one',
      'module' => 'Campaigns',
      'bean_name' => 'Campaign',
      'source' => 'non-db',
    ),
    'currencies' => 
    array (
      'name' => 'currencies',
      'type' => 'link',
      'relationship' => 'opportunity_currencies',
      'source' => 'non-db',
      'vname' => 'LBL_CURRENCIES',
    ),
    'contracts' => 
    array (
      'name' => 'contracts',
      'type' => 'link',
      'vname' => 'LBL_CONTRACTS',
      'relationship' => 'contracts_opportunities',
      'link_type' => 'one',
      'source' => 'non-db',
    ),
    'opportunities_accounts' => 
    array (
      'name' => 'opportunities_accounts',
      'type' => 'link',
      'relationship' => 'opportunities_accounts',
      'source' => 'non-db',
    ),
    'sixtymin_opp_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'sixtymin_opp_c',
      'vname' => 'LBL_SIXTYMIN_OPP',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => NULL,
      'studio' => 'visible',
      'id' => 'Opportunitiessixtymin_opp_c',
      'custom_module' => 'Opportunities',
      'dependency' => NULL,
    ),
    'accepted_by_partner_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'accepted_by_partner_c',
      'vname' => 'LBL_ACCEPTED_BY_PARTNER',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => NULL,
      'options' => 'partner_accepted',
      'studio' => 'visible',
      'id' => 'Opportunitiesaccepted_by_partner_c',
      'custom_module' => 'Opportunities',
      'dependency' => NULL,
    ),
    'partner_contact_notified_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'partner_contact_notified_c',
      'vname' => 'LBL_MATURE_OPP',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => NULL,
      'studio' => 'visible',
      'id' => 'Opportunitiespartner_contact_notified_c',
      'custom_module' => 'Opportunities',
      'dependency' => NULL,
    ),
    'additional_support_cases_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'additional_support_cases_c',
      'vname' => 'Additional_Support_Cases__c',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '50',
      'disable_num_format' => NULL,
      'id' => 'Opportunitiesadditional_support_cases_c',
      'custom_module' => 'Opportunities',
    ),
    'additional_training_credits_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'additional_training_credits_c',
      'vname' => 'Learning_Credits__c',
      'type' => 'int',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => 'This is the number of Learning Credits purchased for this Opportunity.',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '11',
      'disable_num_format' => NULL,
      'id' => 'Opportunitiesadditional_training_credits_c',
      'custom_module' => 'Opportunities',
    ),
    'associated_rep_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'associated_rep_c',
      'vname' => 'Associated_Rep_c',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'associated_rep_c',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesassociated_rep_c',
      'custom_module' => 'Opportunities',
    ),
    'closed_lost_description' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'closed_lost_description',
      'vname' => 'LBL_CLOSED_LOST_DESCRIPTION',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => 'Closed Lost Description',
      'help' => 'Closed Lost Description',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'studio' => 'visible',
      'id' => 'Opportunitiesclosed_lost_description',
      'custom_module' => 'Opportunities',
    ),
    'closed_lost_reason' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'closed_lost_reason',
      'vname' => 'LBL_CLOSED_LOST_REASON',
      'type' => 'multienum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'ClosedLostReason',
      'studio' => 'visible',
      'isMultiSelect' => true,
      'id' => 'Opportunitiesclosed_lost_reason',
      'custom_module' => 'Opportunities',
    ),
    'competitor_1' => 
    array (
      'required' => '1',
      'source' => 'custom_fields',
      'name' => 'competitor_1',
      'vname' => 'LBL_COMPETITOR_1',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiescompetitor_1',
      'custom_module' => 'Opportunities',
    ),
    'competitor_2' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'competitor_2',
      'vname' => 'LBL_COMPETITOR_2',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiescompetitor_2',
      'custom_module' => 'Opportunities',
    ),
    'competitor_3' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'competitor_3',
      'vname' => 'LBL_COMPETITOR_3',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiescompetitor_3',
      'custom_module' => 'Opportunities',
    ),
    'competitor_expiration_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'competitor_expiration_c',
      'vname' => 'LBL_COMPETITOR_EXPIRATION',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => 'The expiration date of the competitive solution for a lost opportunity.',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'id' => 'Opportunitiescompetitor_expiration_c',
      'custom_module' => 'Opportunities',
    ),
    'current_solution' => 
    array (
      'required' => '1',
      'source' => 'custom_fields',
      'name' => 'current_solution',
      'vname' => 'LBL_CURRENT_SOLUTION',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiescurrent_solution',
      'custom_module' => 'Opportunities',
    ),
    'Demo_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'Demo_c',
      'vname' => 'Demo_1',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '1',
      'id' => 'OpportunitiesDemo_c',
      'custom_module' => 'Opportunities',
    ),
    'demo_date_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'demo_date_c',
      'vname' => 'Demo Date_0',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'id' => 'Opportunitiesdemo_date_c',
      'custom_module' => 'Opportunities',
    ),
    'deployment_option' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'deployment_option',
      'vname' => 'LBL_DEPLOYMENT_OPTION',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'DeploymentOption',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesdeployment_option',
      'custom_module' => 'Opportunities',
    ),
    'email_client' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'email_client',
      'vname' => 'LBL_EMAIL_CLIENT',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'Email Client',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesemail_client',
      'custom_module' => 'Opportunities',
    ),
    'evaluation' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'evaluation',
      'vname' => 'LBL_EVALUATION',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiesevaluation',
      'custom_module' => 'Opportunities',
    ),
    'Evaluation_Close_Date_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'Evaluation_Close_Date_c',
      'vname' => 'Evaluation_Close_Date__c',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'OpportunitiesEvaluation_Close_Date_c',
      'custom_module' => 'Opportunities',
    ),
    'evaluation_start_date' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'evaluation_start_date',
      'vname' => 'LBL_EVALUATION_START_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiesevaluation_start_date',
      'custom_module' => 'Opportunities',
    ),
    'extranet_users' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'extranet_users',
      'vname' => 'LBL_EXTRANET_USERS',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'disable_num_format' => '',
      'id' => 'Opportunitiesextranet_users',
      'custom_module' => 'Opportunities',
    ),
    'extranet_value' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'extranet_value',
      'vname' => 'LBL_EXTRANET_VALUE',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'disable_num_format' => '',
      'id' => 'Opportunitiesextranet_value',
      'custom_module' => 'Opportunities',
    ),
    'finance_sales_stage_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'finance_sales_stage_c',
      'vname' => 'Finance_Sales_Stage__c',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '20',
      'options' => 'finance_sales_stage',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesfinance_sales_stage_c',
      'custom_module' => 'Opportunities',
    ),
    'flip_date_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'flip_date_c',
      'vname' => 'Flip_Date_c',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '15',
      'id' => 'Opportunitiesflip_date_c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_Admin_Passwd_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_Admin_Passwd_c',
      'vname' => 'Admin_Password__c',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '16',
      'id' => 'OpportunitiesLBL_Admin_Passwd_c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_Download_Key_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_Download_Key_c',
      'vname' => 'Download_Key_c',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '50',
      'id' => 'OpportunitiesLBL_Download_Key_c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_OnDemand_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_OnDemand_c',
      'vname' => 'OnDemand__c',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '1',
      'id' => 'OpportunitiesLBL_OnDemand_c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_OnSite__c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_OnSite__c',
      'vname' => 'On_Site__c',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '1',
      'id' => 'OpportunitiesLBL_OnSite__c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_Shell_Passwd_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_Shell_Passwd_c',
      'vname' => 'Shell_Password_c',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '16',
      'id' => 'OpportunitiesLBL_Shell_Passwd_c',
      'custom_module' => 'Opportunities',
    ),
    'LBL_Shell_User_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'LBL_Shell_User_c',
      'vname' => 'Shell_User_c',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '50',
      'id' => 'OpportunitiesLBL_Shell_User_c',
      'custom_module' => 'Opportunities',
    ),
    'next_step_dropdown_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'next_step_dropdown_c',
      'vname' => 'LBL_NEXT_STEP_DROPDOWN',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'blank',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => NULL,
      'options' => 'oppty_next_step_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesnext_step_dropdown_c',
      'custom_module' => 'Opportunities',
    ),
    'next_step_due_date' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'next_step_due_date',
      'vname' => 'LBL_NEXT_STEP_DUE_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiesnext_step_due_date',
      'custom_module' => 'Opportunities',
    ),
    'operating_system' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'operating_system',
      'vname' => 'LBL_OPERATING_SYSTEM',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'DeploymentOption',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiesoperating_system',
      'custom_module' => 'Opportunities',
    ),
    'order_number' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'order_number',
      'vname' => 'LBL_ORDER_NUMBER',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiesorder_number',
      'custom_module' => 'Opportunities',
    ),
    'order_type_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'order_type_c',
      'vname' => 'LBL_ORDER_TYPE_C',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '25',
      'id' => 'Opportunitiesorder_type_c',
      'custom_module' => 'Opportunities',
    ),
    'partner_assigned_to_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'partner_assigned_to_c',
      'vname' => 'Partner_Assigned_To_c',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => 'N',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '255',
      'options' => 'partner_assigned_to',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'Opportunitiespartner_assigned_to_c',
      'custom_module' => 'Opportunities',
    ),
    'partner_name' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'partner_name',
      'vname' => 'LBL_PARTNER_NAME',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiespartner_name',
      'custom_module' => 'Opportunities',
    ),
    'renewal_date_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'renewal_date_c',
      'vname' => 'Renewal_Date_c',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => 'This date indicates when this opportunity is up for renewal',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'id' => 'Opportunitiesrenewal_date_c',
      'custom_module' => 'Opportunities',
    ),
    'Revenue_Type_c' => 
    array (
      'required' => '1',
      'source' => 'custom_fields',
      'name' => 'Revenue_Type_c',
      'vname' => 'Revenue_Type__c',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'revenue_type',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'OpportunitiesRevenue_Type_c',
      'custom_module' => 'Opportunities',
    ),
    'sub_delta_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'sub_delta_c',
      'vname' => 'Renewal_Delta_c',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '4',
      'disable_num_format' => NULL,
      'id' => 'Opportunitiessub_delta_c',
      'custom_module' => 'Opportunities',
    ),
    'Term_c' => 
    array (
      'required' => '1',
      'source' => 'custom_fields',
      'name' => 'Term_c',
      'vname' => 'Term__c',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'options' => 'opportunity_term',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'OpportunitiesTerm_c',
      'custom_module' => 'Opportunities',
    ),
    'top20deal_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'top20deal_c',
      'vname' => 'LBL_TOP20DEAL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'comments' => 'Top 20 deal',
      'help' => 'Top 20 deal',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiestop20deal_c',
      'custom_module' => 'Opportunities',
    ),
    'true_up_c' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'true_up_c',
      'vname' => 'LBL_TRUE_UP',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'comments' => '',
      'help' => 'Determines whether or not this is a true up opp.',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 1,
      'len' => '255',
      'id' => 'Opportunitiestrue_up_c',
      'custom_module' => 'Opportunities',
    ),
    'users' => 
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'users',
      'vname' => 'LBL_USERS_1',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => NULL,
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '255',
      'disable_num_format' => NULL,
      'id' => 'Opportunitiesusers',
      'custom_module' => 'Opportunities',
    ),
//EDDY CUSTOMIZATION  - add Score_c field
 'score_c' =>
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'score_c',
      'vname' => 'LBL_SCORE',
      'type' => 'int',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
      'id' => 'Opportunitiesscore_c',
      'custom_module' => 'Opportunities',
    ),
      // jwhitcraft customization - added conflict_c field
    'conflict_c' =>
    array (
      'required' => '0',
      'source' => 'custom_fields',
      'name' => 'conflict_c',
      'vname' => 'LBL_CONFLICT',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 1,
      'len' => '255',
      'size' => '20',
      'id' => 'Opportunitiesconflict_c',
      'custom_module' => 'Opportunities',
    ),
  ),
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'opportunitiespk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
    0 => 
    array (
      'name' => 'idx_opportunities_tmst_id',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'team_set_id',
      ),
    ),
    1 => 
    array (
      'name' => 'idx_opp_name',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'name',
      ),
    ),
    2 => 
    array (
      'name' => 'idx_opp_assigned',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'assigned_user_id',
      ),
    ),
  ),
  'relationships' => 
  array (
    'opportunities_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunities_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'opportunities_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunities_team_count_relationship' => 
    array (
      'lhs_module' => 'Teams',
      'lhs_table' => 'team_sets',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'team_set_id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunities_teams' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'team_set_id',
      'rhs_module' => 'Teams',
      'rhs_table' => 'teams',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'team_sets_teams',
      'join_key_lhs' => 'team_set_id',
      'join_key_rhs' => 'team_id',
    ),
    'opportunities_team' => 
    array (
      'lhs_module' => 'Teams',
      'lhs_table' => 'teams',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'team_id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunity_calls' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'Calls',
      'rhs_table' => 'calls',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Opportunities',
    ),
    'opportunity_meetings' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'Meetings',
      'rhs_table' => 'meetings',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Opportunities',
    ),
    'opportunity_tasks' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'Tasks',
      'rhs_table' => 'tasks',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Opportunities',
    ),
    'opportunity_notes' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'Notes',
      'rhs_table' => 'notes',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Opportunities',
    ),
    'opportunity_emails' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'Emails',
      'rhs_table' => 'emails',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Opportunities',
    ),
    'p1_opportunity_leadaccounts' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'id',
      'rhs_module' => 'LeadAccounts',
      'rhs_table' => 'leadaccounts',
      'rhs_key' => 'opportunity_id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunity_currencies' => 
    array (
      'lhs_module' => 'Opportunities',
      'lhs_table' => 'opportunities',
      'lhs_key' => 'currency_id',
      'rhs_module' => 'Currencies',
      'rhs_table' => 'currencies',
      'rhs_key' => 'id',
      'relationship_type' => 'one-to-many',
    ),
    'opportunities_campaign' => 
    array (
      'lhs_module' => 'campaigns',
      'lhs_table' => 'campaigns',
      'lhs_key' => 'id',
      'rhs_module' => 'Opportunities',
      'rhs_table' => 'opportunities',
      'rhs_key' => 'campaign_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'custom_fields' => true,
);

require_once('include/SugarObjects/VardefManager.php');
VardefManager::createVardef('P1_Partners','P1_Partners', array('default','assignable','team_security','sale'));

?>
