<?php
/*
Touched: sugarcrm/include/ListView/ListViewPagination.tpl

*/
/**
 * Smarty plugin
 * @package Smarty
 * @subpackage plugins
 *
 * This is a Smarty plugin to handle the creation of HTML List elements for Sugar Action Menus.
 * Based on the theme, the plugin generates a proper group of button lists.
 *
 * @param $params array - its structure is
 *     'buttons' => list of button htmls, such as ( html_element1, html_element2, ..., html_element_n),
 *     'id' => id property for ul element
 *     'htmlOptions' =>
 * @param $smarty
 *
 * @return string - compatible sugarActionMenu structure, such as
 * <ul>
 *     <li>html_element1
 *         <ul>
 *              <li>html_element2</li>
 *                  ...
 *              </li>html_element_n</li>
 *         </ul>
 *     </li>
 * </ul>
 * ,which is generated by @see function smarty_function_sugar_menu
 *
 * @author Justin Park (jpark@sugarcrm.com)
 */
function smarty_function_sugar_action_menu($params, &$smarty)
{
    $theme = $params['theme'] ? $params['theme'] : SugarThemeRegistry::current()->name;
    $id = $params['id'];
    $params = $params['attr'];
    if(is_array($params['buttons']) && $theme != 'Classic') {

        $menus = array(
            'html' => array_shift($params['buttons']),
            'items' => array()
        );

        foreach($params['buttons'] as $item) {
            if(strlen($item)) {
                array_push($menus['items'],array(
                   'html' => $item
               ));
            }
        }
        $action_menu = array(
            'id' => $id ? $id : ($params['id'] ? $params['id'] : ''),
            'htmlOptions' => array(
                'class' => $params['class'] && strpos($params['class'], 'clickMenu') !== false  ? $params['class'] : 'clickMenu',
                'name' => $params['name'] ? $params['name'] : ''
            ),
            'submenuHtmlOptions' => array(
                'class' => 'subnav'
            ),
            'items' => array(
                $menus
            )
        );
        require_once('function.sugar_menu.php');
        return smarty_function_sugar_menu($action_menu, $smarty);

    }

    if (is_array($params['buttons'])) {
        return implode(' ', $params['buttons']);
    } else if(is_array($params)) {
        return implode(' ', $params);
    }

    return $params['buttons'];
}

?>