-- //FILE SUGARCRM flav=ent ONLY 
-- project
ALTER TABLE PROJECT ADD (ESTIMATED_START_DATE DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE PROJECT ADD (STATUS VARCHAR2(255 CHAR));
ALTER TABLE PROJECT ADD (PRIORITY VARCHAR2(255 CHAR));
ALTER TABLE PROJECT ADD (IS_TEMPLATE NUMBER(1) DEFAULT 0);
ALTER TABLE PROJECT ADD (ESTIMATED_END_DATE DATE DEFAULT SYSDATE NOT NULL);
UPDATE PROJECT SET STATUS='Draft';
UPDATE PROJECT SET PRIORITY='Medium';

-- project_task
ALTER TABLE PROJECT_TASK ADD (PROJECT_ID VARCHAR2(36 CHAR));
UPDATE PROJECT_TASK SET PROJECT_ID=PARENT_ID;
ALTER TABLE PROJECT_TASK ADD (PROJECT_TASK_ID NUMBER);
ALTER TABLE PROJECT_TASK ADD (RESOURCE_ID CLOB);
ALTER TABLE PROJECT_TASK ADD (PREDECESSORS CLOB);

ALTER TABLE PROJECT_TASK ADD (TIME_START_BACKED DATE);
UPDATE PROJECT_TASK SET TIME_START_BACKED=TIME_START;
ALTER TABLE PROJECT_TASK DROP COLUMN TIME_START;
ALTER TABLE PROJECT_TASK ADD (TIME_START INT);

ALTER TABLE PROJECT_TASK ADD (TIME_FINISH INT);
UPDATE PROJECT_TASK SET TIME_FINISH=CAST(TO_CHAR(TIME_DUE,'HH') AS NUMBER);
ALTER TABLE PROJECT_TASK ADD (DATE_FINISH DATE);
UPDATE PROJECT_TASK SET DATE_FINISH=DATE_DUE;

ALTER TABLE PROJECT_TASK ADD (DURATION INT);
ALTER TABLE PROJECT_TASK ADD (DURATION_UNIT CLOB);
UPDATE PROJECT_TASK SET DURATION_UNIT='Days';

ALTER TABLE PROJECT_TASK ADD (ACTUAL_DURATION NUMBER);
UPDATE PROJECT_TASK SET ACTUAL_DURATION=CEIL(ACTUAL_EFFORT / 8);
ALTER TABLE PROJECT_TASK MODIFY(PERCENT_COMPLETE NUMBER);
UPDATE PROJECT_TASK SET PERCENT_COMPLETE=0 WHERE PRECENT_COMPLETE IS NULL;
ALTER TABLE PROJECT_TASK ADD (PARENT_TASK_ID NUMBER);

ALTER TABLE PROJECT_TASK MODIFY(PARENT_ID VARCHAR2(36 CHAR) NULL);

UPDATE PROJECT_TASK SET MILESTONE_FLAG='1' WHERE MILESTONE_FLAG='on';
UPDATE PROJECT_TASK SET MILESTONE_FLAG='0' WHERE MILESTONE_FLAG='off';

UPDATE PROJECT_TASK SET PROJECT_TASK.TEAM_ID = (SELECT PROJECT.TEAM_ID FROM PROJECT WHERE PROJECT.ID = PROJECT_TASK.PROJECT_ID);