<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');


global $current_user, $dashletData;
include_once('custom/modules/Home/Dashlets/CasePerformance/CasePerformance.en_us.lang.php');

$dashletData['CasePerformance']['searchFields'] = array('status'           => array('default' => array('Closed')),
														'priority'			=> array('default'),
                                                        'date_entered'     => array('default' => ''),
                                                       'date_modified'    => array('default' => ''),
                                                       	'assigned_user_id' => array('type'    => 'assigned_user_name',
                                                                                   'default' => ''),
                                                       	'team_id'          => array('default' => array('')),
                                                       );
$dashletData['CasePerformance']['columns'] = array('case_number' => array('width' => '6',
                                                                          'label' => 'LBL_LIST_NUMBER',
                                                                          'default' => true,
                                                                          'sortable' => true,
                                                                          ),
                                                  'name' => array('width'   => '40',
                                                                  'label'   => 'LBL_LIST_SUBJECT',
                                                                  'link'    => true,
                                                                  'sortable' => false,
                                                                  'default' => true),
                                                  'account_name' => array('width' => '29',
                                                                         'label' => 'LBL_LIST_ACCOUNT_NAME',
                                                                         'sortable' => false,
                                                                         'link' => true,
                                                                         'id' => 'account_id'),
                                                  'status' => array('width'   => '8',
                                                  					'sortable' => false,
                                                                    'label'   => 'LBL_LIST_STATUS'),
                                                  'date_entered' => array('width'   => '15',
                                                  					'sortable' => true,
                                                                    'label'   => 'LBL_LIST_DATE_CREATED'),
                                                  'date_modified' => array('width'   => '15',
                                                  							'sortable' => true,
																			'label'   => 'LBL_LIST_LAST_MODIFIED'),
                                                  'assigned_user_name' => array('width'   => '8',
								                                                  'sortable' => true,
								                                                  'default' => false,
                                                                                'label'   => 'LBL_LIST_ASSIGNED'),
                                                  'first_response' => array('width'   => '15',
                                                  							'sortable' => false,
                                                  							'default' => true,
                                                                          'label'   => $dashletStrings['CasePerformance']['LBL_FIRST_RESPONSE']),
                                                  'resolution_time' => array('width'   => '15',
                                                  							'sortable' => false,
                                                  							'default' => true,
                                                                          'label'   => $dashletStrings['CasePerformance']['LBL_RESOLUTION_TIME']),



                                                  'team_name' => array('width'   => '15',
                                                  						'sortable' => true,
                                                                       'label'   => 'LBL_LIST_TEAM'),

                                                  );
$dashletData['CasePerformance']['holidays'] = array(
                                                                                                        '2007-01-01' => 'New Years',
                                                                                                        '2007-02-19' => 'Presidents Day',
                                                                                                        '2007-05-28' => 'Memorial Day',
                                                                                                        '2007-07-04' => 'Forth of July',
                                                                                                        '2007-09-03' => 'Labor day',
                                                                                                        '2007-11-22' => 'Thanksgiving',
                                                                                                        '2007-11-23' => 'Thanksgiving',
                                                                                                        '2007-12-24' => 'Winter Break',
                                                                                                        '2007-12-25' => 'Winter Break',
                                                                                                        '2007-12-31' => 'New Years Eve',
                                                                                                        '2008-01-01' => 'New Years Day',
                                                                                                        '2008-02-18' => 'Presidents Day',
                                                                                                        '2008-05-26' => 'Memorial Day',
                                                                                                        '2008-07-04' => 'Independence Day',
                                                                                                        '2008-09-01' => 'Labor Day',
                                                                                                        '2008-11-27' => 'Thanksgiving',
                                                                                                        '2008-11-28' => 'Thanksgiving',
                                                                                                        '2008-12-24' => 'Christmas Eve',
                                                                                                        '2008-12-25' => 'Christmas Day',
                                                                                                        '2008-12-31' => 'New Years Eve',
                                                                                                        '2009-01-01' => 'New Years Day',
                                                                                                        '2009-02-16' => 'Presidents Day',
                                                                                                        '2009-05-25' => 'Memorial Day',
                                                                                                        '2009-07-03' => 'Independence Day',
                                                                                                        '2009-09-07' => 'Labor Day',
                                                                                                        '2009-11-26' => 'Thanksgiving',
                                                                                                        '2009-11-27' => 'Thanksgiving',
                                                                                                        '2009-12-24' => 'Christmas Eve',
                                                                                                        '2009-12-25' => 'Christmas Day',
                                                                                                        '2009-12-31' => 'New Years Eve',
                                                                                                        '2010-01-01' => 'New Years',
													);

?>
