<?php
$renamedefs = array(
    'modules' => array(
        'Accounts' => array(
            array('name' => 'LBL_CAMPAIGNS', 'type' => 'plural', 'source' => 'Campaigns'),
            array('name' => 'LBL_CAMPAIGN_ID', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_PARENT_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_PROSPECT_LIST', 'type' => 'singular', 'source' => 'Prospects'),
            array('name' => 'LBL_RLI_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_REVENUELINEITEMS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        ),
        'Administration' => array(
            array('name' => 'LBL_FORECAST_TITLE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_DESC', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_MANAGE_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_MANAGE_FORECASTS_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
        ),
        'Bugs' => array(
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LBL_LIST_MY_BUGS', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LNK_BUG_LIST', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LNK_BUG_REPORTS', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LNK_IMPORT_BUGS', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LNK_NEW_BUG', 'type' => 'singular', 'source' => 'Bugs'),
        ),
        'Calls' => array(
            array('name' => 'LBL_LIST_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
        ),
        'Campaigns' => array(
            array('name' => 'LBL_ACCOUNTS', 'type' => 'plural', 'source' => 'Accounts'),
            array('name' => 'LBL_CONTACTS', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_CAMPAIGN_NAME', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_LOG_ENTRIES_CONTACT_TITLE', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_LOG_ENTRIES_LEAD_TITLE', 'type' => 'plural', 'source' => 'Leads'),
            array('name' => 'LBL_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_PROSPECT_LIST_SUBPANEL_TITLE', 'type' => 'singular', 'source' => 'Targets'),
        ),
        'Cases' => array(
            array('name' => 'LBL_BUGS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
        ),
        'Contacts' => array(
            array('name' => 'LBL_BUGS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Campaigns'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_LEAD_SOURCE', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_ROLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_ROLE_ID', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_PRODUCTS_TITLE', 'type' => 'plural', 'source' => 'Products'),
            array('name' => 'LBL_PROSPECT_LIST', 'type' => 'singular', 'source' => 'Prospects'),
        ),
        'Contracts' => array(
            array('name' => 'LBL_CONTRACT_NAME', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_CONTRACT_TERM', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_DOCUMENTS', 'type' => 'plural', 'source' => 'Documents'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_LIST_CONTRACT_NAME', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_TOTAL_CONTRACT_VALUE', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_TOTAL_CONTRACT_VALUE_USDOLLAR', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LNK_NEW_CONTRACT', 'type' => 'singular', 'source' => 'Contracts'),
        ),
        'Documents' => array(
            array('name' => 'LBL_BUGS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_CONTRACT_NAME', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_CONTRACT_STATUS', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_DET_RELATED_DOCUMENT_VERSION', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_DET_TEMPLATE_TYPE', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_DOC_ID', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_DOC_NAME', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_DOC_REV_HEADER', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_DOC_URL', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_NAME', 'type' => 'singular', 'source' => 'Documents'),
            array('name' => 'LBL_TEMPLATE_TYPE', 'type' => 'singular', 'source' => 'Documents'),
        ),
        'Forecasts' => array(
            array('name' => 'LBL_MODULE_NAME', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LNK_UPD_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_QUOTA', 'type' => 'plural', 'source' => 'Quotas'),
            array('name' => 'LNK_FORECAST_LIST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_HISTORY', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_TIMEPERIOD_NAME', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_ID', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_TIME_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_FORECAST_PIPELINE_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_TIME_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QC_OPPORTUNITY_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_DIRECT_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_ROLLUP_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_UPCOMING_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_OW_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OW_ACCOUNTNAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OW_MODULE_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_TIMEPERIOD_LIST', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SVFS_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_TIMEPERIOD_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_FORECAST_START_DATE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_FDR_WEIGH', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_DV_HEADER', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_TEAM', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_ROLLUP', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TIMPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LV_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_RESET_CHECK', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_QUOTA_ADJUSTED', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_FORECAST_FOR', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_GRAPH_TITLE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_GRAPH_QUOTA_ALTTEXT', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_GRAPH_OPPS_ALTTEXT', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_GRAPH_QUOTA_LEGEND', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_GRAPH_COMMIT_LEGEND', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_GRAPH_OPPS_LEGEND', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_TP_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_CHART_FOOTER', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_CHART_FOOTER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_CHART_FOOTER', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CHART_TITLE', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QUOTA_ID', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_ERROR_NOT_MANAGER', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_COMMITTED_HISTORY_SETUP_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_COMMITTED_HISTORY_UPDATED_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            // BEGIN SUGARCRM flav!=ent ONLY
            array('name' => 'LBL_MY_OPPS_RLI', 'type' => 'plural', 'source' => 'Opportunities'),
            // END SUGARCRM flav!=ent ONLY
            // BEGIN SUGARCRM flav=ent ONLY
            array('name' => 'LBL_MY_OPPS_RLI', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            // END SUGARCRM flav=ent ONLY
            array('name' => 'LBL_EXPECTED_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_DISTANCE_ABOVE_LIKELY_FROM_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_DISTANCE_LEFT_LIKELY_TO_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_DISTANCE_ABOVE_BEST_FROM_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_DISTANCE_LEFT_BEST_TO_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_DISTANCE_ABOVE_WORST_FROM_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_DISTANCE_LEFT_WORST_TO_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_PIPELINE_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_IN_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_TITLE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_MISSING_STAGE_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_MISSING_SALES_STAGE_VALUES', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_ACLS_NO_ACCESS_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_ACLS_NO_ACCESS_MSG', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_BREADCRUMB_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TITLE_FORECAST_SETTINGS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_TITLE_TIMEPERIODS', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TITLE_RANGES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_TITLE_FORECAST_BY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HOWTO_TITLE_FORECAST_BY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_TIMEPERIODS', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_TIMEPERIODS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_TIMEPERIODS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_RANGES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_SCENARIOS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_WORKSHEET_COLUMNS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_HELP_FORECAST_BY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_SETTINGS_SAVED', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIOD_SETUP_NOTICE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIOD_DESC', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIOD_DESC', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_LEAFPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIODS_FORWARD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIODS_FORWARD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIODS_BACKWARD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_TIMEPERIODS_BACKWARD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_CONFIG_GENERAL_FORECAST_BY_TEXT', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_GENERAL_FORECAST_BY_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_FORECASTS_CONFIG_GENERAL_FORECAST_BY_PRODUCT_LINE_ITEMS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_REVENUELINEITEM_NAME', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_FORECASTS_CONFIG_RANGES_SETUP_NOTICE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_RANGES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_SHOW_BINARY_RANGES_DESCRIPTION', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_SHOW_BUCKETS_RANGES_DESCRIPTION', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_SHOW_CUSTOM_BUCKETS_RANGES_DESCRIPTION', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_RANGES_EXCLUDE_INFO', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_CONFIG_WORKSHEET_SCENARIOS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_WIZARD_SUCCESS_MESSAGE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_TABBED_CONFIG_SUCCESS_MESSAGE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_WORKSHEET_SAVE_DRAFT_SUCCESS', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECASTS_WORKSHEET_SAVE_DRAFT_SUCCESS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_WORKSHEET_COMMIT_SUCCESS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_WORKSHEET_COMMIT_SUCCESS_TO', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_UNAUTH_FORECASTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_OPPORTUNITY_STATUS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CAMPAIGN', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_TEAMS', 'type' => 'singular', 'source' => 'Teams'),
            array('name' => 'LBL_DASHLET_FORECAST_NOT_SETUP', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_FORECAST_NOT_SETUP_ADMIN', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_FORECAST_NOT_SETUP_ADMIN', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_PIPELINE_CHART_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_DETAILS_MEETING_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_ASSIGN_QUOTA_BUTTON', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_ASSIGNING_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_QUOTA_ASSIGNED', 'type' => 'plural', 'source' => 'Quotas'),
            array('name' => 'LBL_FORECASTS_NO_ACCESS_TO_CFG_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECASTS_NO_ACCESS_TO_CFG_MSG', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_MY_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_MY_TEAMS_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_FORECAST_NOT_SETUP_ADMIN', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DASHLET_FORECAST_CONFIG_LINK_TEXT', 'type' => 'singular', 'source' => 'Forecasts'),
        ),
        'ForecastManagerWorksheets' => array(
            array('name' => 'LBL_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LNK_UPD_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_QUOTA', 'type' => 'plural', 'source' => 'Quotas'),
            array('name' => 'LNK_FORECAST_LIST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_HISTORY', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_TIMEPERIOD_NAME', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_ID', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_TIME_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_FORECAST_PIPELINE_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_TIME_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QC_OPPORTUNITY_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_DIRECT_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_ROLLUP_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_UPCOMING_FORECASTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_OW_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OW_ACCOUNTNAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OW_MODULE_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_TIMEPERIOD_LIST', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SVFS_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_TIMEPERIOD_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_FORECAST_START_DATE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_FDR_WEIGH', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_DV_HEADER', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_TEAM', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_ROLLUP', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TIMPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LV_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_NOTE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_RESET_CHECK', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_QUOTA_ADJUSTED', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QUOTA_ID', 'type' => 'singular', 'source' => 'Quotas'),
            // BEGIN SUGARCRM flav!=ent ONLY
            array('name' => 'LBL_MY_OPPS_RLI', 'type' => 'plural', 'source' => 'Opportunities'),
            // END SUGARCRM flav!=ent ONLY
            // BEGIN SUGARCRM flav=ent ONLY
            array('name' => 'LBL_MY_OPPS_RLI', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            // END SUGARCRM flav=ent ONLY
        ),
        'ForecastWorksheets' => array(
            array('name' => 'LBL_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LNK_UPD_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_QUOTA', 'type' => 'plural', 'source' => 'Quotas'),
            array('name' => 'LNK_FORECAST_LIST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_HISTORY', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_REVENUELINEITEM_NAME', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LNK_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_ACCOUNTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_TIMEPERIOD_NAME', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_ID', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_TIME_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_FORECAST_PIPELINE_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_TIME_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QC_OPPORTUNITY_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_DIRECT_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_ROLLUP_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_UPCOMING_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_OW_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OW_ACCOUNTNAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OW_MODULE_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_TIMEPERIOD_LIST', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SVFS_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_TIMEPERIOD_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_FORECAST_START_DATE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_FDR_WEIGH', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_DV_HEADER', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_FORECASTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_TEAM', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_ROLLUP', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TIMPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LV_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_NOTE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_RESET_CHECK', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QUOTA', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QUOTA_ID', 'type' => 'singular', 'source' => 'Quotas'),
        ),
        'ForecastSchedule' => array(
            array('name' => 'LBL_MODULE_NAME', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LNK_UPD_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_QUOTA', 'type' => 'plural', 'source' => 'Quotas'),
            array('name' => 'LNK_FORECAST_LIST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_FORECAST_HISTORY', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LNK_FORECAST_HISTORY_TITLE', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_TIMEPERIOD_NAME', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_TIME_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FORECAST_OPP_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_TIME_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_QC_OPPORTUNITY_COUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_QC_DIRECT_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_ROLLUP_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_QC_UPCOMING_FORECASTS', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_OW_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OW_ACCOUNTNAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OW_MODULE_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_TIMEPERIOD_LIST', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SVFS_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_TIMEPERIOD_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FS_FORECAST_START_DATE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FS_MODULE_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_FDR_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_FDR_WEIGH', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_DV_HEADER', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_FORECASTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_MY_TEAM', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_PERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_OPPORTUNITY', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_HEADER', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_FORECAST_ROLLUP', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_DV_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TIMPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LV_TYPE', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_LV_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_COMMIT_NOTE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NO_ACTIVE_TIMEPERIOD', 'type' => 'plural', 'source' => 'Forecasts'),
            array('name' => 'LBL_RESET_CHECK', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_EXPECTED_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
        ),
        'KBDocuments' => array(
            array('name' => 'LBL_CASES', 'type' => 'plural', 'source' => 'Cases'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_CONTRACT_NAME', 'type' => 'plural', 'source' => 'Contracts'),
        ),
        'Leads' => array(
            array('name' => 'LNK_SELECT_###MODULE_PLURAL###', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LNK_SELECT_###MODULE_SINGULAR###', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_ACCOUNT_DESCRIPTION', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CAMPAIGN_ID', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_CAMPAIGN_LEAD', 'type' => 'plural', 'source' => 'Campaigns'),
            array('name' => 'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Campaigns'),
            array('name' => 'LBL_CONTACT_ID', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LEAD_SOURCE', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_LEAD_SOURCE_DESCRIPTION', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OPPORTUNITY_AMOUNT', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_ID', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CONVERTED_ACCOUNT', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LNK_SELECT_ACCOUNTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LNK_NEW_ACCOUNT', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CONVERTED_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CONVERTED_OPP', 'type' => 'singular', 'source' => 'Opportunities'),

        ),
        'Meetings' => array(
            array('name' => 'LBL_LIST_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_JOIN_MEETING', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_PASSWORD', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_TYPE', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_URL', 'type' => 'singular', 'source' => 'Meetings'),
        ),
        'Notes' => array(
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CASE_ID', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LBL_CONTACT_ID', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_CONTACT_NAME', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_NOTE_STATUS', 'type' => 'singular', 'source' => 'Notes'),
            array('name' => 'LBL_OPPORTUNITY_ID', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_PRODUCT_ID', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_QUOTE_ID', 'type' => 'singular', 'source' => 'Quotes'),
        ),
        'Opportunities' => array(
            array('name' => 'LBL_MODULE_NAME', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_VIEW_FORM_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_INVITEE', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CURRENCIES', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CURRENCY_RATE', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_ID', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_NAME', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_SYMBOL', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'UPDATE', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE_VERIFY_TXT', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'UPDATE_DOLLARAMOUNTS_TXT', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'UPDATE_DOLLARAMOUNTS_TXT', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE_CREATE_CURRENCY', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE_VERIFY_NEWCURRENCY', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE_BUG_COUNT', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'UPDATE_BUGFOUND_COUNT', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'UPDATE_MERGE', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'UPDATE_MERGE_TXT', 'type' => 'plural', 'source' => 'Currencies'),
            array('name' => 'UPDATE_MERGE_TXT', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CURRENCY', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CAMPAIGN', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_DUPLICATE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'MSG_DUPLICATE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_NEW_FORM_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_OPPORTUNITY_LIST', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'ERR_DELETE_RECORD', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_TOP_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'NTC_REMOVE_OPP_CONFIRMATION', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'OPPORTUNITY_REMOVE_PROJECT_CONFIRM', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_DEFAULT_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_ACTIVITIES_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Activities'),
            array('name' => 'LBL_LEADS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Leads'),
            array('name' => 'LBL_CONTACTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_DOCUMENTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Documents'),
            array('name' => 'LBL_MY_CLOSED_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_TOTAL_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_CLOSED_WON_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_CAMPAIGN_OPPORTUNITY', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_CAMPAIGN_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CAMPAIGN_LINK', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LNK_IMPORT_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_EXPORT_CAMPAIGN_ID', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_OPPORTUNITY_TYPE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CONTACT_HISTORY_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_PRIMARY_QUOTE_ID', 'type' => 'singular', 'source' => 'Quotes'),
            // BEGIN SUGARCRM flav!=ent ONLY
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_CONTRACTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_PRODUCTS', 'type' => 'plural', 'source' => 'Products'),
            array('name' => 'LBL_RLI', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LNK_OPPORTUNITY_REPORTS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_OPPORTUNITY_REPORTS', 'type' => 'plural', 'source' => 'Reports'),
            array('name' => 'LBL_QUOTES_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Quotes'),
            array('name' => 'LBL_TIMEPERIODS', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_TIMEPERIOD_ID', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            // END SUGARCRM flav!=ent ONLY
            // BEGIN SUGARCRM flav=ent ONLY
            array('name' => 'TPL_RLI_CREATE', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'TPL_RLI_CREATE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'TPL_RLI_CREATE_LINK_TEXT', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_PRODUCTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Products'),
            array('name' => 'LBL_RLI_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_TOTAL_RLIS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CLOSED_RLIS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'NOTICE_NO_DELETE_CLOSED_RLIS', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'NOTICE_NO_DELETE_CLOSED_RLIS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            // END SUGARCRM flav=ent ONLY
            array('name' => 'LBL_QUOTE_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Quotes'),
            array('name' => 'LBL_OPPORTUNITY_ROLE', 'type' => 'singular', 'source' => 'Opportunities'),
        ),
        'PdfManager' => array(
            array('name' => 'LBL_TPL_RLI', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        ),
        'ProductTemplates' => array(
            array('name' => 'LBL_PRODUCT_ID', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_PRODUCT_TEMPLATES', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        ),
        'Products' => array(
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CONTACT_ID', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_LIST_NAME', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_NAME', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_QUOTE_ID', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_RELATED_PRODUCTS', 'type' => 'plural', 'source' => 'Products'),
            array('name' => 'LBL_URL', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_REVENUELINEITEM_NAME', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_REVENUELINEITEMS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_REVENUELINEITEM_ID', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_REVENUELINEITEM', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_PRODUCTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contacts'),
        ),
        'ProjectTask' => array(
            array('name' => 'LBL_PARENT_NAME', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_PROJECT_ID', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_PROJECT_NAME', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_PROJECT_TASK_ID', 'type' => 'singular', 'source' => 'Projects'),
        ),
        'Project' => array(
            array('name' => 'LBL_BUGS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Bugs'),
            array('name' => 'LBL_CONTACTS_RESOURCE', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_PROJECT_HOLIDAYS_TITLE', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_PROJECT_TASKS_SUBPANEL_TITLE', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LNK_NEW_PROJECT', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LNK_PROJECT_LIST', 'type' => 'singular', 'source' => 'Projects'),
        ),
        'Quotes' => array(
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_QUOTE_NUM', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_LIST_PRODUCT_NAME', 'type' => 'singular', 'source' => 'Products'),
            array('name' => 'LBL_REVENUELINEITEMS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        ),
        'Quotas' => array(
            array('name' => 'LNK_FORECAST_LIST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_FORECAST_HISTORY', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LNK_UPD_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_MODULE_FORECASTS_NAME', 'type' => 'plural', 'source' => 'Forecasts'),
        ),
        'RevenueLineItems' => array(
            array('name' => 'LBL_CAMPAIGN_PRODUCT', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_MODULE_NAME', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LNK_NEW_REVENUELINEITEM', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_NEW_FORM_TITLE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_RELATED_PRODUCTS', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_LEAD_SOURCE', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_LIST_NAME', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_LIST_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_LIST_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_LIST_QUOTE_NAME', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_LIST_PRODUCT_TEMPLATE', 'type' => 'singular', 'source' => 'ProductTemplates'),
            array('name' => 'LBL_NAME', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_QUOTE_NAME', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_ASSOCIATED_QUOTE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CONTACT_NAME', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LNK_REVENUELINEITEM_LIST', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LNK_NEW_REVENUELINEITEM', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CURRENCY', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_ID', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_NAME', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_SYMBOL', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_DEFAULT_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_ACCOUNT_ID', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CONTACT_ID', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_NOTES_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Notes'),
            array('name' => 'LBL_DOCUMENTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Documents'),
            array('name' => 'LBL_CONTRACTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_QUOTES_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Quotes'),
            array('name' => 'LBL_LEADS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Leads'),
            array('name' => 'LBL_CONTACTS_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_CONTRACTS', 'type' => 'plural', 'source' => 'Contracts'),
            array('name' => 'LBL_PRODUCT_TEMPLATES', 'type' => 'plural', 'source' => 'ProductTemplates'),
            array('name' => 'LBL_PRODUCT_CATEGORIES', 'type' => 'plural', 'source' => 'ProductCategories'),
            array('name' => 'LBL_PRODUCT_TYPES', 'type' => 'plural', 'source' => 'ProductTypes'),
            array('name' => 'LBL_PRODUCT_TEMPLATE', 'type' => 'singular', 'source' => 'ProductTemplates'),
            array('name' => 'LBL_PRODUCT_TEMPLATE_ID', 'type' => 'singular', 'source' => 'ProductTemplates'),
            array('name' => 'LBL_QUOTE_ID', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_QUOTE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_OPPORTUNITY_ID', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            //BEGIN SUGARCRM flav=ent ONLY
            array('name' => 'LBL_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_CALCULATED_LINE_ITEM_AMOUNT', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            //END SUGARCRM flav=ent ONLY
            array('name' => 'LBL_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CURRENCY_SYMBOL_NAME', 'type' => 'singular', 'source' => 'Currencies'),
            //BEGIN SUGARCRM flav!=ent ONLY
            array('name' => 'LBL_RLI_SUBPANEL_TITLE', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            //END SUGARCRM flav!=ent ONLY
            array('name' => 'LNK_IMPORT_REVENUELINEITEMS', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_EXPORT_CURRENCY_ID', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_CURRENCY_RATE', 'type' => 'singular', 'source' => 'Currencies'),
            array('name' => 'LBL_COMMIT_STAGE_FORECAST', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_CONVERT_TO_QUOTE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CONVERT_TO_QUOTE_INFO_MESSAGE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CONVERT_TO_QUOTE_INFO_MESSAGE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CONVERT_INVALID_RLI', 'type' => 'plural', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CONVERT_INVALID_RLI', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CONVERT_INVALID_RLI_PRODUCT', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CONVERT_INVALID_RLI_PRODUCT', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CONVERT_TO_QUOTE_ERROR_MESSAGE', 'type' => 'singular', 'source' => 'RevenueLineItems'),
            array('name' => 'LBL_CONVERT_TO_QUOTE_ERROR_MESSAGE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'SAVE_RLI_QUOTE_NOTICE', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'WARNING_MERGE_RLIS_WITH_DIFFERENT_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
        ),
        'Reports' => array(
            array('name' => 'LNK_NEW_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LNK_NEW_ACCOUNT', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LNK_NEW_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LNK_NEW_CASE', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LNK_NEW_NOTE', 'type' => 'singular', 'source' => 'Notes'),
            array('name' => 'LNK_NEW_CALL', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'LNK_NEW_EMAIL', 'type' => 'singular', 'source' => 'Emails'),
            array('name' => 'LNK_NEW_MEETING', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LNK_NEW_TASK', 'type' => 'singular', 'source' => 'Tasks'),
            array('name' => 'LBL_ACCOUNTS', 'type' => 'plural', 'source' => 'Accounts'),
            array('name' => 'LBL_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'LBL_CONTACTS', 'type' => 'plural', 'source' => 'Contacts'),
            array('name' => 'LBL_LEADS', 'type' => 'plural', 'source' => 'Leads'),
            array('name' => 'LBL_ACCOUNT', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_LEAD', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_ACCOUNT_REPORTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CONTACT_REPORTS', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_OPPORTUNITY_REPORTS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_CASE_REPORTS', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LBL_BUG_REPORTS', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LBL_LEAD_REPORTS', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_QUOTE_REPORTS', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_CALL_REPORTS', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'LBL_MEETING_REPORTS', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_TASK_REPORTS', 'type' => 'singular', 'source' => 'Tasks'),
            array('name' => 'LBL_EMAIL_REPORTS', 'type' => 'singular', 'source' => 'Emails'),
            array('name' => 'LBL_MY_TEAM_ACCOUNT_REPORTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_MY_TEAM_OPPORTUNITY_REPORTS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MY_TEAM_CONTACT_REPORTS', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_MY_TEAM_CASE_REPORTS', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LBL_MY_TEAM_BUG_REPORTS', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LBL_MY_TEAM_LEAD_REPORTS', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_MY_TEAM_QUOTE_REPORTS', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_MY_TEAM_CALL_REPORTS', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'LBL_MY_TEAM_MEETING_REPORTS', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_MY_TEAM_TASK_REPORTS', 'type' => 'singular', 'source' => 'Tasks'),
            array('name' => 'LBL_MY_TEAM_EMAIL_REPORTS', 'type' => 'singular', 'source' => 'Emails'),
            array('name' => 'LBL_MY_TEAM_FORECAST_REPORTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_MY_TEAM_PROSPECT_REPORTS', 'type' => 'singular', 'source' => 'Prospects'),
            array('name' => 'LBL_MY_TEAM_CONTRACT_REPORTS', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_MY_TEAM_PROJECT_TASK_REPORTS', 'type' => 'singular', 'source' => 'Projects'),
            array('name' => 'LBL_MY_ACCOUNT_REPORTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_MY_OPPORTUNITY_REPORTS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_MY_CONTACT_REPORTS', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_MY_CASE_REPORTS', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LBL_MY_BUG_REPORTS', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LBL_MY_LEAD_REPORTS', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_MY_QUOTE_REPORTS', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_MY_CALL_REPORTS', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'LBL_MY_MEETING_REPORTS', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_MY_TASK_REPORTS', 'type' => 'singular', 'source' => 'Tasks'),
            array('name' => 'LBL_MY_EMAIL_REPORTS', 'type' => 'singular', 'source' => 'Emails'),
            array('name' => 'LBL_MY_FORECAST_REPORTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_PUBLISHED_ACCOUNT_REPORTS', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_PUBLISHED_CONTACT_REPORTS', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_PUBLISHED_OPPORTUNITY_REPORTS', 'type' => 'singular', 'source' => 'Opportunities'),
            array('name' => 'LBL_PUBLISHED_CASE_REPORTS', 'type' => 'singular', 'source' => 'Cases'),
            array('name' => 'LBL_PUBLISHED_BUG_REPORTS', 'type' => 'singular', 'source' => 'Bugs'),
            array('name' => 'LBL_PUBLISHED_LEAD_REPORTS', 'type' => 'singular', 'source' => 'Leads'),
            array('name' => 'LBL_PUBLISHED_QUOTE_REPORTS', 'type' => 'singular', 'source' => 'Quotes'),
            array('name' => 'LBL_PUBLISHED_QUOTA_REPORTS', 'type' => 'singular', 'source' => 'Quotas'),
            array('name' => 'LBL_PUBLISHED_CALL_REPORTS', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'LBL_PUBLISHED_MEETING_REPORTS', 'type' => 'singular', 'source' => 'Meetings'),
            array('name' => 'LBL_PUBLISHED_TASK_REPORTS', 'type' => 'singular', 'source' => 'Tasks'),
            array('name' => 'LBL_PUBLISHED_EMAIL_REPORTS', 'type' => 'singular', 'source' => 'Emails'),
            array('name' => 'LBL_PUBLISHED_FORECAST_REPORTS', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'LBL_PUBLISHED_PROSPECT_REPORTS', 'type' => 'singular', 'source' => 'Prospects'),
            array('name' => 'LBL_TEAM', 'type' => 'singular', 'source' => 'Teams'),
            array('name' => 'LBL_CONTRACT_REPORTS', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_MY_CONTRACT_REPORTS', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'LBL_PUBLISHED_CONTRACT_REPORTS', 'type' => 'singular', 'source' => 'Contracts'),
            array('name' => 'DEFAULT_REPORT_TITLE_1', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'DEFAULT_REPORT_TITLE_2', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'DEFAULT_REPORT_TITLE_3', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'DEFAULT_REPORT_TITLE_4', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'DEFAULT_REPORT_TITLE_5', 'type' => 'singular', 'source' => 'Calls'),
            array('name' => 'DEFAULT_REPORT_TITLE_6', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_7', 'type' => 'plural', 'source' => 'Cases'),
            array('name' => 'DEFAULT_REPORT_TITLE_8', 'type' => 'plural', 'source' => 'Cases'),
            array('name' => 'DEFAULT_REPORT_TITLE_9', 'type' => 'plural', 'source' => 'Cases'),
            array('name' => 'DEFAULT_REPORT_TITLE_10', 'type' => 'plural', 'source' => 'Cases'),
            array('name' => 'DEFAULT_REPORT_TITLE_17', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_13', 'type' => 'plural', 'source' => 'Tasks'),
            array('name' => 'DEFAULT_REPORT_TITLE_14', 'type' => 'plural', 'source' => 'Calls'),
            array('name' => 'DEFAULT_REPORT_TITLE_15', 'type' => 'plural', 'source' => 'Meetings'),
            array('name' => 'DEFAULT_REPORT_TITLE_16', 'type' => 'plural', 'source' => 'Accounts'),
            array('name' => 'DEFAULT_REPORT_TITLE_18', 'type' => 'plural', 'source' => 'Leads'),
            array('name' => 'DEFAULT_REPORT_TITLE_43', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'DEFAULT_REPORT_TITLE_44', 'type' => 'plural', 'source' => 'Accounts'),
            array('name' => 'DEFAULT_REPORT_TITLE_45', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_46', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_47', 'type' => 'plural', 'source' => 'Calls'),
            array('name' => 'DEFAULT_REPORT_TITLE_48', 'type' => 'plural', 'source' => 'Meetings'),
            array('name' => 'DEFAULT_REPORT_TITLE_49', 'type' => 'plural', 'source' => 'Tasks'),
            array('name' => 'DEFAULT_REPORT_TITLE_50', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_51', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_52', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_53', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_56', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_57', 'type' => 'plural', 'source' => 'Opportunities'),
            array('name' => 'DEFAULT_REPORT_TITLE_58', 'type' => 'singular', 'source' => 'Forecasts'),
            array('name' => 'DEFAULT_REPORT_TITLE_59', 'type' => 'plural', 'source' => 'Opportunities'),
        ),
        'Targets' => array(
            array('name' => 'LBL_ACCOUNT_NAME', 'type' => 'singular', 'source' => 'Accounts'),
            array('name' => 'LBL_CAMPAIGN_ID', 'type' => 'plural', 'source' => 'Campaigns'),
            array('name' => 'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE', 'type' => 'singular', 'source' => 'Campaigns'),
            array('name' => 'LBL_PROSPECT_LIST', 'type' => 'singular', 'source' => 'Prospects'),
        ),
        'Tasks' => array(
            array('name' => 'LBL_CONTACT', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CONTACT_ID', 'type' => 'singular', 'source' => 'Contacts'),
            array('name' => 'LBL_CONTACT_PHONE', 'type' => 'singular', 'source' => 'Contacts'),
        ),
        'TimePeriods' => array(
            array('name' => 'LBL_TP_TYPE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_MODULE_NAME', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_MODULE_NAME_SINGULAR', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_MODULE_TITLE', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SEARCH_FORM_TITLE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LIST_FORM_TITLE', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_NEW_FORM_TITLE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_NEW_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LNK_TIMEPERIOD_LIST', 'type' => 'plural', 'source' => 'TimePeriods'),
            array('name' => 'LBL_SEARCH_TP_NAME', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'ERR_TIME_PERIOD_DATE_RANGE', 'type' => 'singular', 'source' => 'TimePeriods'),
            array('name' => 'LBL_LIST_WARNING', 'type' => 'singular', 'source' => 'TimePeriods'),
        ),
    ),
    'global' => array(
        // Forecast(s)
        array('name' => 'LBL_DASHLET_FORECAST_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_DASHLET_FORECAST_PARETO_CHART_NAME', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_SCREEN_2_DESCRIPTION_670', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_SCREEN_2_DESCRIPTION_670', 'type' => 'plural', 'source' => 'TimePeriods'),
        array('name' => 'LBL_TOUR_SCREEN_2_DESCRIPTION_670', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOUR_SCREEN_3_DESCRIPTION_670', 'type' => 'singular', 'source' => 'TimePeriods'),
        array('name' => 'LBL_TOUR_SCREEN_3_DESCRIPTION_670', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_SCREEN_4_DESCRIPTION_670', 'type' => 'singular', 'source' => 'Quotas'),
        array('name' => 'LBL_TOUR_SCREEN_5_DESCRIPTION_670', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_SCREEN_5_DESCRIPTION_670', 'type' => 'singular', 'source' => 'TimePeriods'),
        array('name' => 'LBL_TOUR_SCREEN_6_DESCRIPTION_670', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOUR_SCREEN_6_DESCRIPTION_670', 'type' => 'singular', 'source' => 'Quotas'),
        array('name' => 'LBL_TOUR_FORECAST_INTRO', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_FORECASTS_TIMEPERIODS', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_FORECASTS_PROGRESS', 'type' => 'singular', 'source' => 'Quotas'),
        array('name' => 'LBL_TOUR_FORECASTS_CHART', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_DASHLET_FORECASTS_CHART', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_DASHLET_FORECASTS_DESC', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_DASHLET_FORECASTS_DETAILS_DESC', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_FORECAST_WORKSHEETS', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_FORECAST_WORKSHEET', 'type' => 'singular', 'source' => 'Forecasts'),
        array('name' => 'LBL_TOUR_FEATURES_670', 'type' => 'plural', 'source' => 'Forecasts'),
        array('name' => 'LBL_DASHLET_FORECASTS_DETAILS', 'type' => 'plural', 'source' => 'Forecasts'),
        // Revenue Line Item(s)
        //BEGIN SUGARCRM flav=ent ONLY
        array('name' => 'LBL_DASHLET_TOP10_SALES_OPPORTUNITIES_NAME', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_CHART_DESC', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_MY_OPP', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_MY_TEAMS_OPP', 'type' => 'plural', 'source' => 'RevenueLineItems'),
        //END SUGARCRM flav=ent ONLY
        // Opportunities
        //BEGIN SUGARCRM flav!=ent ONLY
        array('name' => 'LBL_DASHLET_TOP10_SALES_OPPORTUNITIES_NAME', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_CHART_DESC', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_MY_OPP', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOP10_OPPORTUNITIES_MY_TEAMS_OPP', 'type' => 'plural', 'source' => 'Opportunities'),
        //END SUGARCRM flav!=ent ONLY
        array('name' => 'ERR_OPPORTUNITY_NAME_DUPE', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'ERR_OPPORTUNITY_NAME_MISSING', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_OPPORTUNITIES', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOUR_SCREEN_2_DESCRIPTION_670', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_TOUR_SCREEN_6_DESCRIPTION_670', 'type' => 'plural', 'source' => 'Opportunities'),
        array('name' => 'LBL_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_EMAIL_QC_OPPORTUNITIES', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_OPPORTUNITY_METRICS', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_CREATE_OPPORTUNITY', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_DASHLET_OPPORTUNITY_NAME', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_DASHLET_OPPORTUNITY_DESCRIPTION', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'ERR_QUOTE_CONVERTED', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_QUOTE_TO_OPPORTUNITY_LABEL', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'LBL_QUOTE_TO_OPPORTUNITY_TITLE', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'ERR_OPPORTUNITY_NAME_DUPE', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'ERR_OPPORTUNITY_NAME_MISSING', 'type' => 'singular', 'source' => 'Opportunities'),
        array('name' => 'ERR_QUOTE_CONVERTED', 'type' => 'singular', 'source' => 'Opportunities'),
        // Quote(s)
        array('name' => 'ERR_QUOTE_CONVERTED', 'type' => 'singular', 'source' => 'Quotes'),
        array('name' => 'LBL_QUOTE_TO_OPPORTUNITY_LABEL', 'type' => 'singular', 'source' => 'Quotes'),
        array('name' => 'LBL_QUOTE_TO_OPPORTUNITY_TITLE', 'type' => 'singular', 'source' => 'Quotes'),
        array('name' => 'LBL_GENERATE_QUOTE', 'type' => 'singular', 'source' => 'Quotes'),
        array('name' => 'LBL_QUOTES_SHIP_TO', 'type' => 'plural', 'source' => 'Quotes'),
        array('name' => 'LBL_QUOTES', 'type' => 'plural', 'source' => 'Quotes'),
        // Time Periods
        array('name' => 'ERR_TIMEPERIOD_ALREADY_LEAF', 'type' => 'plural', 'source' => 'TimePeriods'),
        array('name' => 'ERR_TIMEPERIOD_TYPE_DOES_NOT_EXIST', 'type' => 'plural', 'source' => 'TimePeriods'),
        array('name' => 'LBL_CURRENT_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
        array('name' => 'LBL_PREVIOUS_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
        array('name' => 'LBL_NEXT_TIMEPERIOD', 'type' => 'singular', 'source' => 'TimePeriods'),
        array('name' => 'LBL_TOUR_FORECASTS_TIMEPERIODS', 'type' => 'singular', 'source' => 'TimePeriods'),

    ),
);
